### ISSUE TITLE
Verify template configuration with interfacetable_v3t plugin

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingaweb2-module-graphite#102]
We need to verify if the template language works with more complex plugin outputs like `interfacetable_v3t plugin`

Ref: http://www.tontonitch.com/tiki/tiki-index.php?page=Nagios+plugins+-+interfacetable_v3t

**Comment by Al2Klimov** [comment]
Icinga 2 works w/ plugin outputs. We only work w/ perfdata written by Icinga 2. And yes, our default template is generic enough for any kind of numbers.
