### ISSUE TITLE
Page jumps to top on auto refresh

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingaweb2-module-graphite#104]
## Expected Behavior
On auto refresh, the page should stay at the same point.

## Current Behavior
Page jumps to the top of detail view.

## Steps to Reproduce (for bugs)
1. Open detail view of a service with more then two graphs, eg. `icinga`
2. Select a time range from the quick time picker, eg. `1 day`
3. Open all graphs with the `Show more` button
4. Scroll down
5. Wait for auto refresh

## Context
If no time range is selected, this works as expected.

**Comment by Al2Klimov** [comment]
As discussed w/ @lippserd and @bobapple (offline):

This is an IW2 problem – on "Show more" click "Show more" gets focussed and that focus bends the post-autorefresh page position. So where to put the focus...?

**Comment by Al2Klimov** [comment]
@bobapple Does https://github.com/Icinga/icingaweb2/pull/3295 solve the problem for you?

**Comment by Al2Klimov** [comment]
Solved via that PR
