### ISSUE TITLE
[dev.icinga.com #13473] Restrictions

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-graphite#11]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13473

**Created by dgoetz on 2016-12-08 10:36:43 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-08 10:36:43 +00:00 (in Redmine)_

---

I would like to have restrictions applied to the Graphite Overview so a user can only select hosts he could access in the monitoring and other modules, too.

**Comment by Al2Klimov** [comment]
Note for the future myself: The only needed, but not secured action is /show/graph which gets already transformed monitored objects names.

Solution:
1. reverse transform to pattern
2. query IDO by this pattern
3. check the (already restricted) result and restrict respectively

If one really has the hosts `mysql1.mybase` and `mysql1_mybase` – it's their problem.
