### ISSUE TITLE
add LineMode as default

### ISSUE THREAD

**Issue by pogii123** [Icinga/icingaweb2-module-graphite#112]
Hi, 

I want to have all graphs connected when there's a metric missing, I tried to add the LineMode in the default template but it came out it won't affect all graphs. 

As I don't want to overwrite all templates which are shipped by the module. So is there any way to make this work? 

```
graphite]# cat templates/default.ini
[default-host.metrics_filters]
value = "$host_name_template$.perfdata.$perfdata$.value"

[default-host.urlparams]
areaAlpha = "0.5"
areaMode = "all"
title = "$perfdata$"
yUnitSystem = "none"
lineMode = "connected"

[default-host.functions]
value = "alias(color($metric$, '#1a7dd7'), 'value')"
```

## Expected Behavior
the default template will provide basic options for all graphs

## Current Behavior
default template wont affect basic configuration

## Your Environment
* Module version (System - About): 0.9.0
* Icinga Web 2 version and modules (System - About): 2.5.0
* Icinga 2 version (`icinga2 --version`): 2.8
* Operating System and version: Rhel 7.4
* Webserver, PHP versions: PHP Version 7.1 / Apache 2.4

**Comment by Al2Klimov** [comment]
Hello @pogii123,

does c872636 fulfill your needs?

Best,
AK
