### ISSUE TITLE
Fatal error: Class 'Icinga\Util\Json' 

### ISSUE THREAD

**Issue by mustafadw** [Icinga/icingaweb2-module-graphite#114]
Fatal error: Class 'Icinga\Util\Json' not found in /usr/share/icingaweb2/modules/graphite/library/Graphite/Graphing/MetricsQuery.php on line 110

## Your Environment

* Module version (debian- 3.16.51-2):
* Icinga 2 version (`icinga2 -- r2.7.0-1`):
* Webserver, PHP versions: apache2 2.4.10 , php 5.6.30

**Comment by lippserd** [comment]
I think you're running a old Icinga Web 2 version. Please check the dependencies of this module.
