### ISSUE TITLE
[dev.icinga.com #13475] Graphical Resize

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-graphite#12]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13475

**Created by dgoetz on 2016-12-08 10:37:51 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-08 10:37:51 +00:00 (in Redmine)_

---

I would like to have the option to set the size of the graphs in the UI and not only as URL parameter.

**Comment by Al2Klimov** [comment]
@bobapple To implement or not to implement?

**Comment by bobapple** [comment]
@dgoetz what's the point on setting the size of the graph? If the graph has a sane width and fills the detailview, how does it help to change that size?

**Comment by Al2Klimov** [comment]
"the graph has a sane width and fills the detailview" – now it does: 1f5d59a

**Comment by bobapple** [comment]
The current implementation sets the width to 100%
I think this is the best solution currently
