### ISSUE TITLE
Fill in space between performance data's

### ISSUE THREAD

**Issue by pogii123** [Icinga/icingaweb2-module-graphite#123]
Hi,

it would be nice, if the space's in the performance graph, will be filled when the `LineMode` is set to `connected`.

The following screenshot will maybe explain that more.

![image](https://user-images.githubusercontent.com/14888191/35613315-086cf4f8-066c-11e8-96d5-13b017439c7e.png)

These gaps are not colored blue. Is there any reason for that?

Regards,
pogii123

## Context
My customers are asking me, why there are gaps...

## Your Environment
* Module version (System - About): 0.9.0
* Icinga Web 2 version and modules (System - About): 2.5.0
* Icinga 2 version (`icinga2 --version`): 2.8.1
* Operating System and version: RHEL 7.4
* Webserver, PHP versions: php 7.1, apache 2.4.x

**Comment by Al2Klimov** [comment]
Hello @pogii123,

yes, there is: because there's no data for that time.
For alternatives on graph rendering please consult the Graphite docs.

Best,
AK

**Comment by lbetz** [comment]
I have always problems to explain that to customers. And I think it's hard to understand why we've a closing line but the area below isn't filled. So please fill these areas or disable this 'feature'. As an alternative it would be ok to enable/disable it in our configuration.

**Comment by Al2Klimov** [comment]
By filling that space we would literally lie to the users. A monitoring tool shall not do this.

**Comment by mjbrooks** [comment]
The line is merely a visual indicator of the trend. The fill area shows the actual data.

Filling the area with false information is bad form. The only way to properly eliminate the gaps is to not have gaps in the data you are collecting. :D

**Comment by Al2Klimov** [comment]
Recently had a similar case with net traffic stats from InfluxDB visualized by Grafana. In that case even filling "linear" gave you false information, I had to fill with 0.

**Comment by Al2Klimov** [comment]
@bobapple Would you "fill with 0" here by default?

**Comment by Al2Klimov** [comment]
![redis net io opt](https://user-images.githubusercontent.com/6053266/47493371-65660180-d84f-11e8-9250-227a065399f8.png)
