### ISSUE TITLE
Inserts -dummy in URL - and scaling of graph

### ISSUE THREAD

**Issue by avik78** [Icinga/icingaweb2-module-graphite#125]
## Expected Behavior
I have set this in config.ini

[graphite]
url = "http://myhostname:8000/"

And I would expect it to show the graph normally

## Current Behavior
But it inserts a "graph-dummy" in the URL, so the picture is empty 

http://myhostname/icingaweb2/graphite/graph-dummy/

If I edit /usr/share/icingaweb2/modules/graphite/library/Graphite/Web/Widget/Graphs/Service.php

And change the function protected function getDummyImageBaseUrl()
from
        return Url::fromPath('graphite/graph-dummy/service');

to:
        return Url::fromPath('graphite/graph/service');

it looks good, but I have no idea what the purpose of the -dummy is.

Also - when I remove "-dummy", the graph comes up, but it tries to scale the photo, so when using a wide screen, the letters/numbers gets a bit messed up.

## Your Environment

* Module version (System - About): 0.9.0
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: apache2-2.4.18-2ubuntu3.5/PHP7.1

**Comment by bobapple** [comment]
@avik78 Is javascript enabled in your browser?

**Comment by avik78** [comment]
Yes - it looks like the scaling part works now - so everything the graphins looks good now. So this part can safely be ignored - that was a human error on my part.

but - I still don't understand the -dummy part in the URL.




Ole Anders

**Comment by bobapple** [comment]
@avik78 we need that dummy container to scale the graph properly.

**Comment by kajla** [comment]
I have this problem too.

- Module version (System - About): 1.0.1
- Icinga Web 2 version and modules (System - About): 2.5.1
- Icinga 2 version (icinga2 --version): r2.8.2-1
- Operating System and version: SLES 12 SP3
- Webserver, PHP versions: apache2-2.4.23/PHP7.0.7

**Comment by SungurovDV** [comment]
Check /etc/hosts !
У меня несколько серверов и на одном сервере возникла подобная проблема. После прописывания собственного имени в /etc/hosts проблема исчезла.
