### ISSUE TITLE
[dev.icinga.com #13477] PDF export

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-graphite#13]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13477

**Created by dgoetz on 2016-12-08 10:39:44 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-08 10:39:44 +00:00 (in Redmine)_

---

I would like to do a PDF export of the Graphite Overview like other views offer it.

**Comment by Al2Klimov** [comment]
@dgoetz Now you have the usual link "PDF" which actually generates a PDF... which is far from being production-ready (it looks like utter crap). But I won't fix this right now – I'll wait for green light from @lippserd.

**Comment by Al2Klimov** [comment]
As discussed w/ @nilmerg:

No real progress has been made in the framework's PDF export, so we have to wait for this anyway.

**Comment by bobapple** [comment]
I'm closing this issue. The PDF export functionality needs to be implemented in icingaweb2, not module-wise
