### ISSUE TITLE
Graph templates: omit lineWidth=2

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2-module-graphite#131]
## Expected Behavior

![goodgraph2](https://user-images.githubusercontent.com/6053266/35861209-24866da6-0b47-11e8-8ea2-2b01df2eb2b3.png)

## Current Behavior

![badgraph2](https://user-images.githubusercontent.com/6053266/35861227-2f795dfe-0b47-11e8-8d98-f6fad789e2ba.png)

## Context

#71

## Your Environment

Latest bleeding edge stuff only.

**Comment by Al2Klimov** [comment]
@bobapple What's your opinion on this?

**Comment by flourish86** [comment]
I'd stick with the current behavior with lineWidth=2, as it seems to be more balanced to me.

**Comment by bobapple** [comment]
I aggree with @flourish86, `lineWidth=2` looks better to me

**Comment by return2alfred** [comment]
@Al2Klimov Hi,giant,I must say so,could you tell me or us how could I make the change of graph background color just the same like yours.Cause this new version didn't mention it.Really appricate your help me for building a better icingaweb ui.Thanks.

**Comment by dnsmichi** [comment]
@return2alfred 

Please stop flooding our issue tracker with random issue comments. Join the community support channels with your question.
