### ISSUE TITLE
Graph templates tester

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2-module-graphite#132]
## Current Behavior

As a graph template writer or reviewer I have to
1. get the check plugin
2. provide the actual stuff to check (HTTPd, MySQL cluster, ...)
3. write Icinga config

## Expected Behavior

I don't have to do anything of those.

## Possible Solution

A CLI command which loads all templates (as we already do) and generates Icinga config based on that which just uses printf (no check plugins required) to output random (but "nice-looking") perfdata (no "actual stuff to check" required).

## Context

#71

## Your Environment

Latest bleeding edge stuff only.

**Comment by Al2Klimov** [comment]
@bobapple What's your opinion on this?

**Comment by bobapple** [comment]
I understand that this is a nice to have and fun to develop thing, but I doubt there's anyone out there creating templates for check plugins they don't even use. Therefore, I'm against building such a feature. 

I would however find it great if there would be some more feedback on the web interface if a template is not working.

**Comment by Al2Klimov** [comment]
I'm gonna implement this anyway as
1. I need this now for #71
2. It doesn't harm anything

**Comment by Al2Klimov** [comment]
Also: even if I use a plugin – maybe it outputs "too boring" graphs
