### ISSUE TITLE
Clicking hosts does nothing in Icingaweb2 under the graphite section

### ISSUE THREAD

**Issue by mdeguzis** [Icinga/icingaweb2-module-graphite#136]
## Expected Behavior

Clicking the host section in Icingaweb2 under graphite should show the graphs. 

## Current Behavior

Clicking hosts does nothing in Icingaweb2 under the graphite section. If I intentionally spell the host wrong, I do get the main page noting the 2 hosts can't get to the url. If I leave that sit,,l update the url on the icinga host and click refresh, it just spins forever. 

I can reach the graphite dashboard fine. Graphite is running via the official image via http, and icingaweb is running via https. 
## Steps to Reproduce (for bugs)

1. Run the default official graphite docker container
2. Run Icingaweb2 and add the module
3. Configure the host and port

Are there logs I can look at? I don't see anything of note in the incga2 or icingaweb2 logs. 
## Your Environment

* Module version (System - About):
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

**Comment by mtdeguzis** [comment]
I noticed this call being made from the http access log, but no error is show I see:

```
172.18.0.1 - - [11/Feb/2018:03:40:47 +0000] "GET /icingaweb2/application-state HTTP/1.1" 200 - "https://localhost:8484/icingaweb2/config/modules" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36"
```

Could it be a permissions issue with some kind of resource?

**Comment by mtdeguzis** [comment]
Module version (System - About):  0.9.0
Icinga Web 2 version and modules (System - About): 2.5.1
Icinga 2 version (icinga2 --version): r2.8.1-1
Operating System and version: RHEL 7.4 64 Bit
Webserver, PHP versions: PHP 5.4.16 (cli) (built: Oct  4 2017 03:09:42)

**Comment by mtdeguzis** [comment]
Icinga + Icingaweb is runngin via docker via https, connected to the official docker container for graphite.

**Comment by mtdeguzis** [comment]
carbon.log:

```
11/02/2018 04:15:59 :: [listener] MetricLineReceiver connection with 127.0.0.1:38014 established
11/02/2018 04:15:59 :: [listener] MetricLineReceiver connection with 127.0.0.1:38014 closed cleanly
11/02/2018 04:15:59 :: [tagdb] Tagging carbon.aggregator.graphite_geisinger_edu-a.memUsage
11/02/2018 04:15:59 :: [tagdb] Tagged carbon.aggregator.graphite_geisinger_edu-a.memUsage in 0.00506997108459
11/02/2018 04:16:02 :: [listener] MetricLineReceiver connection with 172.18.0.3:55834 established
11/02/2018 04:16:02 :: [listener] invalid line received from client 172.18.0.3:55834, ignoring [GET /metrics/expand?query=icinga2.gdchdpmn03drlx_geisinger_edu.host.ssl.perfdata.%2A.value HTTP/1.1]
11/02/2018 04:16:02 :: [listener] invalid line received from client 172.18.0.3:55834, ignoring [User-Agent: icingaweb2-module-graphite]
11/02/2018 04:16:02 :: [listener] invalid line received from client 172.18.0.3:55834, ignoring [Authorization: Basic cm9vdDpyb290]
11/02/2018 04:16:02 :: [listener] invalid line received from client 172.18.0.3:55834, ignoring [Host: icinga-graphite-01:2003]
11/02/2018 04:16:02 :: [listener] invalid line received from client 172.18.0.3:55834, ignoring []
```

**Comment by mtdeguzis** [comment]
Trying to connect on the default port 80 for graphite gives me 
```
Fatal error: Call to undefined function iplx\Http\curl_reset() in /usr/local/share/icingaweb2/modules/graphite/library/vendor/iplx/Http/Client.php on line 183
```

**Comment by mtdeguzis** [comment]
Checked for php curl:

vim /var/www/html/phpcurltest.php
```

```
<?php

// Script to test if the CURL extension is installed on this server

// Define function to test
function _is_curl_installed() {
    if  (in_array  ('curl', get_loaded_extensions())) {
        return true;
    }
    else {
        return false;
    }
}

// Ouput text to user based on test
if (_is_curl_installed()) {
  echo "cURL is <span style=\"color:blue\">installed</span> on this server";
} else {
  echo "cURL is NOT <span style=\"color:red\">installed</span> on this server";
}
?>
```
https://localhost:8484/phpcurltest.php
```

**Comment by lazyfrosch** [comment]
Since you are on RHEL 7, [curl_reset()](https://secure.php.net/manual/de/function.curl-reset.php) was introduced in PHP 5.5, so your system PHP does not support it.

You have to make sure you are running Icinga Web 2 with PHP-FPM and PHP 7.x, see [Upgrading to Icinga Web 2 2.5.x](https://www.icinga.com/docs/icingaweb2/latest/doc/80-Upgrading/#upgrading-to-icinga-web-2-25x)

**Comment by mtdeguzis** [comment]
We don't use systemd inside our Docker containers, which just adds unnecessary complexity and is against the principals of Docker microservices anyway. The docs note removing php/php-common, but php-comon is a dependency of php-fpm.

**Comment by lazyfrosch** [comment]
The packages are using `rh-php71` scl by default, so that is not the normal `php-fpm`, that is installed under `/opt/rh/...` -  https://www.icinga.com/docs/icingaweb2/latest/doc/02-Installation/#upgrading-to-fpm

**Comment by mtdeguzis** [comment]
Ah, I see. Hmm getting:

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```
Rechecking  /etc/httpd/conf.d/icingaweb2.conf

**Comment by lazyfrosch** [comment]
If you need further help you should check out https://monitoring-portal.org/ which is a good community support resource.

I'm not sure what the initial problem in this issue is, the user did not supply any version information.

Closing this, please check with community support :)

**Comment by mtdeguzis** [comment]
OK, opened up https://monitoring-portal.org/t/trying-to-start-icingaweb2-wth-php-fpm-internal-server-error/1154
