### ISSUE TITLE
[dev.icinga.com #13479] Only a single filter can be used

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-graphite#14]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13479

**Created by dgoetz on 2016-12-08 10:42:52 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-08 10:42:52 +00:00 (in Redmine)_

---

It seems that there was a change which only allows to create only one filter in the Graphite Overview. I would expect to be able to use multiple filters.

**Comment by Al2Klimov** [comment]
@dgoetz Things have changed since 6490db1 – see https://youtu.be/rG14P-wtubM. Do these changes fit your needs?

**Comment by dgoetz** [comment]
Video does not show this part very good, but if filter now works like in the monitoring module it should be good.

**Comment by Al2Klimov** [comment]
Fine. (Pro tip: watch w/ 0.5x speed)
