### ISSUE TITLE
Error when trying to open Configuration Tab

### ISSUE THREAD

**Issue by fesch89** [Icinga/icingaweb2-module-graphite#140]
Stacktrace
Updated Icingaweb to the newest Version 2.5.1
Updated Graphite Module to Version 0.9.0

## Expected Behavior
Open the Configuration Tab of Graphite

## Current Behavior
Error Message:
Fatal error: Uncaught ErrorException: Undefined index: file in /usr/share/php/Icinga/Exception/IcingaException.php:77 Stack trace: #0 /usr/share/php/Icinga/Exception/IcingaException.php(77): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined index...', '/usr/share/php/...', 77, Array) #1 /usr/share/icingaweb2/application/controllers/ErrorController.php(98): Icinga\Exception\IcingaException::getConfidentialTraceAsString(Object(ErrorException)) #2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\ErrorController->errorAction() #3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('errorAction') #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response)) #5 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response)) #6 /usr/share/ in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 332

## Your Environment

* Module version (System - About): 0.9.0
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.8.1
* Operating System and version: CentOS7 
* Webserver, PHP versions: Apache2, PHP-7.1

**Comment by lippserd** [comment]
@Al2Klimov Is this fixed w/ the latest changes to `IcingaException::getConfidentialTraceAsString()`?

**Comment by Al2Klimov** [comment]
Yes.

**Comment by willd** [comment]
This error seems to break new installs. When will this fix be pushed out to the icinga-xenial repo?

**Comment by willd** [comment]
Turns out I had made a configuration error that made this happen. I had
misspelled the timezone in php.ini.

Sorry to bother you devs :)

**Comment by Al2Klimov** [comment]
@TryTryAgain It's an Icinga Web 2 issue and (IMO) no module could work-around it even if it wanted to.

**Comment by cflinspach** [comment]
I got the same error caused by the same thing as @willd (miss spelled time zone) on the login page though.

**Comment by dnsmichi** [comment]
Try icinga/icingaweb2#3358

**Comment by cflinspach** [comment]
@dnsmichi We were able to fix it by correcting the spelling of the timezone. Incase anyone else finds this issue though I wanted to point out that misspelling can effect more than just the Configuration Tab.
