### ISSUE TITLE
Documentation for dynamically rendering graph for each perfdata

### ISSUE THREAD

**Issue by kirjastojk** [Icinga/icingaweb2-module-graphite#141]
The doc/04-Templates.md page now states

> To dynamically render a graph for each performance data label found, define a macro in place for the actual perfdata-label:
>
>$host_name_template$.perfdata.$perfdata_label$.value

but this doesn't really tell me how the ini file should be in order to dynamically have all the perfdata in a graph. Could an example or further instructions be added?

**Comment by kirjastojk** [comment]
I found a hack which let's me do one graph for all the perfdata automatically:

[apache1.graph]
check_command = "mysql_table_size"

[apache1.urlparams]
title = "Table sizes"
target = "$service_name_template$.perfdata.*.value"

[apache1.metrics_filters]
value = "$service_name_template$"

**Comment by Al2Klimov** [comment]
Hello @kirjastojk and thank you for reporting!

There are two possible use cases for this:
1. A lot of hardcoded perfdata labels
2. Perfdata labels containing dynamic identifiers of "service elements" – e.g. disks or NICs

In both cases I'd like to see as less curves as possible in one graph for the sake of clarity. (See also #134)

If your template is like [icinga](https://github.com/Icinga/icingaweb2-module-graphite/blob/7b6827aef19c8b4b5af17fc6266d70bf28db6506/templates/icinga.ini) (has a lot of curves), I'd really recommend you to either (1) let the default template do the work for you (one graph per curve) or (2) to study the plugin (example output or source code) and write a template for it – with a few curves per graph (logically grouped, e.g. like icinga).

If your check observes a theoretically unlimited number of "service elements" (disks, NICs, etc.), I'd recommend you to write a template like [disk](https://github.com/Icinga/icingaweb2-module-graphite/blob/7b6827aef19c8b4b5af17fc6266d70bf28db6506/templates/disk.ini) or [interfacetable](https://github.com/Icinga/icingaweb2-module-graphite/blob/7b6827aef19c8b4b5af17fc6266d70bf28db6506/templates/interfacetable.ini) – a hardcoded number of graphs per "service element".


If you'd apply you hack to icinga or interfacetable, you'd get e.g. 20 curves in one graph – and that's no fun. All info contained in a graph should be understandable by one quick look at it. Your hack in combination with one (or both) of the two use cases would be the opposite.

Best,
AK

**Comment by Al2Klimov** [comment]
@bobapple Do you agree w/ me?

**Comment by kirjastojk** [comment]
Thanks @Al2Klimov. My check can return different $perfdata_label$ everytime but there is always a maximum of five of $perfdata_label$. However, usually in my check the $perfdata_label$ labels stay the same for weeks. What do you think about supporting such use case?

Now the "hack" I posted earlier gets all the old $perfdata_label$ from the previous checks so the graph might get polluted pretty soon. So a way to **only include the current perfata_labels** to the graph would be the improvement needed to support this use case.

Supporting this use case I propose would probably need a quite big changes to how the templating works now with macros. Therefore, I'm not even myself very convinced whether to support this.

**Comment by Al2Klimov** [comment]
Hello @kirjastojk,

I'd really like to have a look at your check plugin's code (at least at some representative outputs) before I decide anything.

Best,
AK

**Comment by kirjastojk** [comment]
@Al2Klimov here it is: <http://paste.debian.net/plain/1015482>. It gets the five biggest tables in a database and returns those tables sizes as perfdata. So as the biggest tables might change over time then the perfdata labels might change too.

**Comment by Al2Klimov** [comment]
This is clearly a collection of "service elements" – MySQL DB tables. I'd recommend you to select not only the top 5 most critical, but all of them (`s/LIMIT 5//`) and to write your template according to [the doc you quoted](https://github.com/Icinga/icingaweb2-module-graphite/issues/141#issue-300209442).
