### ISSUE TITLE
Graphs are only viewable for time <= 2 days

### ISSUE THREAD

**Issue by Reavermaster** [Icinga/icingaweb2-module-graphite#144]
The standard view for the graphs provide viewable data but after the time range is changed to more than two days no graphs will be shown - the normal graphite-web interface provides data for that time range.

## Expected Behavior
Time Range change should provide graphs

## Current Behavior
Graphs will only be shown for a time range <= 2 days

## Possible Solution
-

## Steps to Reproduce (for bugs)
1. Select a service check that provides perfdata for graphite
2. Change the time range for the shown graph to a value greater than 2 days
3. Graph view with matching timeline but without data will be shown

## Context
-

## Your Environment
* Module version (System - About): 0.9.0 - latest git clone
* Icinga Web 2 version and modules (System - About): 2.5.0
* Icinga 2 version (`icinga2 --version`): r2.8.0-1
* Operating System and version: CentOS 7.4.1708
* Webserver, PHP versions: Apache 2.4.6 / PHP 7.1.9

**Comment by Al2Klimov** [comment]
Hello @Reavermaster and thank you for reporting!

The only difference between the time ranges are the start and end timestamps passed to Graphite Web. So that's most likely a Graphite problem.

Best
AK

@bobapple Do you agree?

**Comment by bobapple** [comment]
@Reavermaster for me it sounds like an aggregation (storage schema) issue within your graphite installation. What version of graphite are you using?

**Comment by Reavermaster** [comment]
I think it was a problem with the storage on that node.

I have installed a complete new one and dublicated the complete configuration.

For now it looks like everything works.

I think this can be closed for now.
