### ISSUE TITLE
i cant load graphite in the icinga2 Missing "graphite.url"

### ISSUE THREAD

**Issue by AkatsukiPain** [Icinga/icingaweb2-module-graphite#146]
The error appear like below
![image](https://user-images.githubusercontent.com/14358073/37394130-a4a846c4-27a5-11e8-9e88-90dc499d8bf0.png)
This is the Graphite interface:
![image](https://user-images.githubusercontent.com/14358073/37394156-bb7f6742-27a5-11e8-983c-542e8dfdaa83.png)

i dont know how to load the graphite in the icinga2, i have added a config.ini to the folder as intrustion: 
https://www.zhmurko.com/services/icinga2-monitoring/icingaweb2-graphite-integration/ and it dont work.

**Comment by Al2Klimov** [comment]
Hello @AkatsukiPain and thank you for reporting!

I'm afraid the linked manual is neither official nor up-to-date. Please see [the official docs](https://github.com/Icinga/icingaweb2-module-graphite/blob/master/doc/03-Configuration.md) for the configuration.

Best,
AK

**Comment by Al2Klimov** [comment]
As discussed w/ @bobapple (offline):

Nice to have: Better error message on missing config.

**Comment by Al2Klimov** [comment]
Resolved by #149
