### ISSUE TITLE
[dev.icinga.com #13481] Allow more and custom timeranges

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-graphite#15]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13481

**Created by dgoetz on 2016-12-08 10:46:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-08 11:55:55 +00:00 (in Redmine)_

---

I would like to have more possible time ranges to select from and also perhaps set a custom timerange in the Graphite Overview. Also it should be possible to not only use the last e.g. four hours instead other end times than now should be possible.

**Comment by Al2Klimov** [comment]
@dgoetz Things have changed since 6490db1 – see https://youtu.be/rG14P-wtubM (press pause once the host graph list has been loaded). Do these changes fit your needs?

**Comment by dgoetz** [comment]
Looks good to me and I hope it fits customers needs, too.

**Comment by Al2Klimov** [comment]
Fine. (Programs never fit all their customers' needs ;-) )
