### ISSUE TITLE
Git tag and module.info do not align

### ISSUE THREAD

**Issue by leeclemens** [Icinga/icingaweb2-module-graphite#152]
Git tag label/version and module.info version do not align

## Expected Behavior
The version in module.info should match the tag's version number

## Current Behavior
module.info shows version 0.9.0 for tag v1.0.0

## Possible Solution
module.info version should match the version shown as the tag's version

**Comment by Al2Klimov** [comment]
Hello @leeclemens and thank you for reporting!

This has been fixed by #158 (v1.0.1).

Best,
AK
