### ISSUE TITLE
Graphs for services with $ (dollar-sign) in the name do not work.

### ISSUE THREAD

**Issue by ramilehti** [Icinga/icingaweb2-module-graphite#156]
## Expected Behavior
Expected a graph for my service with a dollar sign in the service name. 

## Current Behavior
But this fails because icinga has replaced all dollar signs in the "perfdata name" with underscores. 
Graphite is queried 

/metrics/expand?query=icinga2.hostname_changed.services.SMB_ad.disk_smb.perfdata.ad_.max

The query should be 
/metrics/expand?query=icinga2.hostname_changed.services.SMB_ad.disk_smb.perfdata.ad%24.max

I can view the graph in Graphite browser.

## Possible Solution
Do not replace $ signs with _  in the service name but with proper hex escapes. %24 in this case.

## Steps to Reproduce (for bugs)

1. Create a service for a hidden smb share that has a dollar sign in the name in Icinga2 
2. Try to access the graphite graph for it.

## Environment
* Module version (System - About): graphite | 0.9.0
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.2-1
* Operating System and version: Ubuntu 16.04.4 LTS
* Webserver, PHP versions: Apache 2.4.18, PHP 7.0

**Comment by dnsmichi** [comment]
Graphite itself does not allow to store metrics which contain `$` or `%` as these are directly put onto the filesystem. Therefore Icinga 2 already replaces the metric name, there's not much the web module can do about it.

**Comment by ramilehti** [comment]
My version of Graphite does store the values on disk. With $ in the name and all. As I said earlier I can view trhe graph in Graphite browser. Also the data is sent from Icinga through GraphiteWriter OK. 

My questions are: 
Does Icinga handle the dollar sign one way when it deals with GraphiteWriter and Icingaweb another way when it deals with Graphite module?
Is Icinga the one to blame here then or Icingaweb?

**Comment by Al2Klimov** [comment]
Hello @ramilehti and thank you for reporting!

Such names don't work (yet) because the dollar sign is a special character "everywhere" in the Graphite mod. config.
I already have an idea how to fix this one...

Best,
AK
