### ISSUE TITLE
Different values after upgrade from version 0.9 to version 1.0.1 or 1.1.0

### ISSUE THREAD

**Issue by akqopensystems** [Icinga/icingaweb2-module-graphite#163]
## Expected Behavior
Prior to updating the graphite module to version 1.0.1 or 1.1.0, the values on disk were shown correspondingly, e.g. Mi, Gi etc. We didn`t do any changes to the templates for example disk.ini. 

## Current Behavior
After updating the graphite module, only bytes values for disk appear to be displayed.

**Version: 0.9**
![grafik](https://user-images.githubusercontent.com/23358770/38542097-414fe3f0-3ca1-11e8-9e73-e49f6713f05b.png)

**Version 1.0.1 or 1.1.0**
![grafik](https://user-images.githubusercontent.com/23358770/38542058-29a3b894-3ca1-11e8-8862-5dfd4f339ab8.png)

## Context
We use nrpe.

## Your Environment

* Module version (System - About): current master git version (1.1.0)
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.8.2
* Graphite (carbon, web, whisper) version: carbon-c-relay-2.6-1.el7, whisper-0.9.16-1.el7
* Operating System and version: RHEL-7.4
* Webserver, PHP versions: httpd-2.4.6-67.el7, rh-php71

**Comment by dnsmichi** [comment]
Since you are using the git master, please check this https://github.com/Icinga/icingaweb2-module-graphite/blob/master/doc/05-Troubleshooting.md and provide the debug details.

**Comment by akqopensystems** [comment]
It looks like after the upgrade from the graphite-module, the check command "nrpe" don`t use the template "disk.ini" anymore.

**Extract debug log from nrpe**
```
Graphs assembling process record

+ Icinga check command: 'nrpe'
+ Obscured check command: NULL
+ Applying templates for check command 'nrpe'
+ Applying default templates, excluding previously used metrics
++ Not applying template 'default-host'
++ Applying template 'default-service'
+++ Fetched 1 metric(s) from 'http://server.xxxxxx.de/metrics/expand?query=icinga2.host1.services.available_volume_space_boot.nrpe.perfdata.%2A.value'
+++ Excluded 0 metric(s)
+++ Combined 1 metric(s) to 1 chart(s)
```

**Extract debug log from agent based**

```
Graphs assembling process record

+ Icinga check command: 'disk-windows'
+ Obscured check command: NULL
+ Applying templates for check command 'disk-windows'
++ Applying template 'disk'
+++ Fetched 1 metric(s) from 'http://server.xxxxxx.de/metrics/expand?query=icinga2.host2.services.available_volume_space.disk-windows.perfdata.%2A.value'
+++ Fetched 1 metric(s) from 'http://server.xxxxxx.de/metrics/expand?query=icinga2.host2.services.available_volume_space.disk-windows.perfdata.%2A.max'
+++ Excluded 0 metric(s)
+++ Combined 2 metric(s) to 1 chart(s)
+ Applying default templates, excluding previously used metrics
++ Not applying template 'default-host'
++ Applying template 'default-service'
+++ Fetched 1 metric(s) from 'http://server.xxxxxx.de/metrics/expand?query=icinga2.host2.services.available_volume_space.disk-windows.perfdata.%2A.value'
+++ Excluded 1 metric(s)
+++ Combined 0 metric(s) to 0 chart(s)
```

How can we fix it?

**Comment by akqopensystems** [comment]
Thanks for your support, that helped. Everything looks okay so far.
