### ISSUE TITLE
Icinga2web Graphs sample are not shown at Host

### ISSUE THREAD

**Issue by redbob365** [Icinga/icingaweb2-module-graphite#164]
Hi,

I enabled Graphite module in icingaweb2.
but when I chose any host, at overview I see this error:

![Erro do Graphite](https://imgur.com/a/DNZXZ)

* Module version (System - About): 0.0.0.5
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.2-1
* Operating System and version: Ubuntu 16.04.4 64bit
* Webserver, PHP versions: 7.0.28

**Comment by redbob365** [comment]
I cannot edit my issue. That's the correct link to the image:
![Erro do Graphite](https://imgur.com/download/t5mvgdK)

**Comment by Al2Klimov** [comment]
Hello @redbob365 and thank you for reporting!

Please try the latest version of Icinga Web 2.

Best,
AK
