### ISSUE TITLE
 change/improvement - More than one graphite.

### ISSUE THREAD

**Issue by belsebubben** [Icinga/icingaweb2-module-graphite#165]
We have an environment with many zones, all writing to their own graphite, it would be great to have the ability to add more than one graphite and to look for graphs there as well. One alternative could be to have one per zone. So for instance objects belonging to zone1 could look for data in graphite1 for instance.

thanks for the good work

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Module version (System - About):
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Graphite (carbon, web, whisper) version:
* Operating System and version:
* Webserver, PHP versions:

**Comment by Al2Klimov** [comment]
@bobapple Is there something like a "Graphite Web multiplexer/router" like "mongos" for MongoDB?

**Comment by Al2Klimov** [comment]
Thank you @widhalmt.
