### ISSUE TITLE
interrupted lines

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2-module-graphite#167]
## Expected Behavior
Lines are drawed completly at max value of the graph

## Current Behavior
The Line is interrupted at ~12:50 an ~13:05in the Screenshot
![image](https://user-images.githubusercontent.com/25796110/40232007-71a3bf76-5a9d-11e8-8dc2-1a3187483101.png)

## Context
standard hostalive_check is used

## Your Environment

* Icingaweb2 Graphite Module Version (System - About):
Version | 1.0.1
-- | --
3a98d2c47354b76f246225593c0a1c52caedbdfd
* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version
2.5.3
Git Commit
ca7e886b820f0145999fdf7377f5c4132301eada

* Icinga 2 version (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.5.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Graphite (carbon, web, whisper) version: 
graphite-web.noarch 0.9.16-2.el7
python-carbon.noarch 0.9.16-1.el7
python-whisper.noarch 0.9.16-1.el7

* Operating System and version:
CentOS Linux release 7.4.1708 (Core)

* Webserver, PHP versions:
httpd.x86_64 2.4.6-80.el7.centos
icingaweb2-vendor-lessphp.noarch
php-Icinga.noarch 2.5.3-1.el7.icinga
rh-php71-php-cli.x86_64 7.1.8-1.el7
rh-php71-php-common.x86_64 7.1.8-1.el7
rh-php71-php-fpm.x86_64 7.1.8-1.el7
rh-php71-php-gd.x86_64 7.1.8-1.el7
rh-php71-php-intl.x86_64 7.1.8-1.el7
rh-php71-php-json.x86_64 7.1.8-1.el7
rh-php71-php-ldap.x86_64 7.1.8-1.el7
rh-php71-php-mbstring.x86_64 7.1.8-1.el7
rh-php71-php-mysqlnd.x86_64 7.1.8-1.el7
rh-php71-php-pdo.x86_64 7.1.8-1.el7
rh-php71-php-pgsql.x86_64 7.1.8-1.el7
rh-php71-php-xml.x86_64 7.1.8-1.el7
rh-php71-php-zip.x86_64 7.1.8-1.el7
rh-php71-runtime.x86_64 1-1.el7

**Comment by Al2Klimov** [comment]
Hello @cstegm and thank you for reporting!

As far as I can see the lines are not interrupted, but they're cutted off because they're being rendered outside the viewport. Graphite decides [automatically](https://graphite.readthedocs.io/en/latest/render_api.html#ymax) how to draw these and I'm afraid we can't control that.

I'd update Graphite Web to the latest version and open an issue on the Graphite Web tracker if updating doesn't help.

Best,
AK
