### ISSUE TITLE
PHP 7.2: "count(): Parameter must be an array or an object that implements Countable"

### ISSUE THREAD

**Issue by Wuestengecko** [Icinga/icingaweb2-module-graphite#168]
## Expected Behavior
Graphs should be showing up as usual.

## Current Behavior
Wherever graphs are supposed to be drawn, there is the error message:

    count(): Parameter must be an array or an object that implements Countable

In individual host/service views, as well as the Graphite -> Hosts/Services menus in the navigation bar.

## Possible Solution
Unfortunately I have no idea where exactly the error happens. If you can tell me how to find out, I'd be happy to help.

## Steps to Reproduce (for bugs)
1. Install Icingaweb2 + this module
2. Login to the web interface
3. Navigate to a host or service that provides perfdata
4. Instead of the graphs, you will see the above error

(Note: the Graphs section also shows up on hosts/services that _don't_ provide any performance data, with the same error.)

## Context
I'm trying to set up a new Icingaweb2 instance with graphite graphs.

## Your Environment
* Module version (System - About): 1.0.1 (also happens on git version: 1.0.1-10-g3a98d2c)
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): r2.8.4-1
* Graphite (carbon, web, whisper) version: graphite-api 1.1.3-4, go-carbon 0.12.0-1
* Operating System and version: Arch Linux
* Webserver, PHP versions: Apache 2.4.33, PHP 7.2.5

## Screenshot
This screenshot is taken from a host view:
![screenshot_2018-05-24 icinga web](https://user-images.githubusercontent.com/1579756/40490588-33969310-5f6c-11e8-83f4-b0c600dfd70f.png)

**Comment by dnsmichi** [comment]
Breaking changes in PHP 7.2: http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types

Specifically, one needs to look into all count() calls inside the code and adopt them in a compatible way.

**Comment by lippserd** [comment]
Could you please add a stack trace?

**Comment by lippserd** [comment]
Thanks for the trace. We'll look into this asap.

**Comment by Farfaday** [comment]
Would it be possible to do new release including that fix ?
Many Thanks!

**Comment by Al2Klimov** [comment]
@bobapple Do you think we have enough for a v1.1?

**Comment by Al2Klimov** [comment]
Our master isn't as stable as Director after all.
