### ISSUE TITLE
No graphs in Overview Host/Service

### ISSUE THREAD

**Issue by TorstenCX** [Icinga/icingaweb2-module-graphite#169]
## Current Behavior
Graphs don't show up in Overview -> Host/Service. 
They're only visible under the Graphite main-menu.

![overview](https://user-images.githubusercontent.com/39727341/40649865-2bfedf9e-6332-11e8-9474-b60f84b34516.png)
![graphite](https://user-images.githubusercontent.com/39727341/40649866-2c1ec016-6332-11e8-9b64-60b8f5459014.png)

## Your Environment

* Module version (System - About):
1.0.1
* Icinga Web 2 version and modules (System - About):
2.5.3

director: 1.4.3
graphite: 1.0.1
monitoring 2.5.3

* Icinga 2 version (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.4 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-116-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: 9c880c2f42f5

* Graphite (carbon, web, whisper) version:
graphite-carbon/xenial,xenial,now 0.9.15-1
graphite-web/xenial,xenial,now 0.9.15+debian-1
python-whisper/xenial,xenial,now 0.9.15-1

* Webserver, PHP versions:
apache2-bin/xenial-updates,xenial-security,now 2.4.18-2ubuntu3.8

PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by dnsmichi** [comment]
Can you inspect the detail view graph and look into the dev console if there are any errors?

**Comment by TorstenCX** [comment]
Thanks for your fast response. 
It was my fault. After refreshing/reloading the page everything works as expected.
