### ISSUE TITLE
(SOLVED) Composite Tooling Corporation 404 error

### ISSUE THREAD

**Issue by syswombat** [Icinga/icingaweb2-module-graphite#174]
Installed Graphite and got a error 

## Expected Behavior
Should show a Graf
but shows only a Composite Tooling Corporation 404 error

## Current Behavior
![icinga_graf-error](https://user-images.githubusercontent.com/3279451/42432496-5396ed30-833a-11e8-9a28-a7215aebe66f.png)

## Your Environment

* Module version (System - About): 0.0.0.5 
* Icinga Web 2 version and modules (System - About): 
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.0-1)

* Icinga 2 version (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.0-1)

Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-6-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.2.1
  Build host: amalia

* Graphite (carbon, web, whisper) version: (pip list)
carbon (0.9.15)
graphite-web (0.9.12)
whisper (0.9.15)

* Operating System and version: 
ystem information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-6-amd64
  Architecture: x86_64

* Webserver, PHP versions:
PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by Al2Klimov** [comment]
"Solved" – closed.
