### ISSUE TITLE
difference Documentation and my system

### ISSUE THREAD

**Issue by syswombat** [Icinga/icingaweb2-module-graphite#175]
https://github.com/Icinga/icingaweb2-module-graphite/blob/master/doc/03-Configuration.md
in the Doc is a description where to config
Configuration > Modules > graphite > Backend

## Expected Behavior
to have a Button or a link like described

## Current Behavior
i only have Module: graphite | Configuration

and in the Configuration path

In case your graphite web url differs from http://graphite.com/render/? or if your graphite prefix differs from "icinga" please create a config file in /etc/icingaweb2/modules/graphite/config.ini following this example:

has not the Modules graphite 
all my modul are  there --> /usr/share/icingaweb2/modules

so i am a bit confused

## Possible Solution
none

## Steps to Reproduce (for bugs)
new installed Icinga2 and Web with graphite

## Context
would like to be able to config the base url to have some nice graph

## Your Environment

* Icinga Web 2 version and modules (System - About):
how to find out?

* Icinga 2 version (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.0-1)

Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
License GPLv2+: GNU GPL version 2 or later http://gnu.org/licenses/gpl2.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
Installation root: /usr
Sysconf directory: /etc
Run directory: /run
Local state directory: /var
Package data directory: /usr/share/icinga2
State path: /var/lib/icinga2/icinga2.state
Modified attributes path: /var/lib/icinga2/modified-attributes.conf
Objects path: /var/cache/icinga2/icinga2.debug
Vars path: /var/cache/icinga2/icinga2.vars
PID path: /run/icinga2/icinga2.pid

System information:
Platform: Debian GNU/Linux
Platform version: 9 (stretch)
Kernel: Linux
Kernel version: 4.9.0-6-amd64
Architecture: x86_64

Build information:
Compiler: GNU 6.2.1
Build host: amalia

* Graphite (carbon, web, whisper) version:
Graphite (carbon, web, whisper) version: (pip list)
carbon (0.9.15)
graphite-web (0.9.12)
whisper (0.9.15)
Modul 0.0.0.5
* Operating System and version:

* Webserver, PHP versions:
PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
Apache/2.4.25 (Debian)

**Comment by dnsmichi** [comment]
You're using a different graphite module from [findmypast](https://github.com/findmypast/icingaweb2-module-graphite). Please open an issue over there, and also follow their docs.
