### ISSUE TITLE
on the View not allways the same time and no change on week, month, year

### ISSUE THREAD

**Issue by syswombat** [Icinga/icingaweb2-module-graphite#176]
Hello
if i do have a look at the Graph,
and select the  [10 minutes,1 hour,12 hours,1 day,1 week,1 month,1 year] View 
the view on the bootom is sometimes wrong
10min shows the right time a 24:00 view
1hour is also ok
12hour is also ok
1day show the english time with 12AM or 6pm
1 Weel shows the same as 1day and also wrong time
1month shows the same as 1day and also wrong time
1 year shows the same as 1day and also wrong time

have a nice day
vinc

## Expected Behavior
the same 24hour time view
and also some other information on week, month and year

## Current Behavior
1day show the english time with 12AM or 6pm
1 Weel shows the same as 1day and also wrong time
1month shows the same as 1day and also wrong time
1 year shows the same as 1day and also wrong time

## Possible Solution
sorry not a coder ;-)

## Your Environment

* Module version (System - About):
graphite	0.0.0.5
* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version: 2.5.3
* Icinga 2 version (`icinga2 --version`):
# icinga2 --version
[2018-07-13 20:45:22 +0200] warning/icinga-app: Sysconfig file '/etc/sysconfig/icinga2' cannot be read. Using default values.
[2018-07-13 20:45:22 +0200] warning/icinga-app: Sysconfig file '/etc/sysconfig/icinga2' cannot be read. Using default values.
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-6-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: f7d481dc25b9

* Graphite (carbon, web, whisper) version:
* Operating System and version:
debian 9
* Webserver, PHP versions:
HP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
Apache/2.4.25 (Debian)

**Comment by Al2Klimov** [comment]
Hello @syswombat and thank you for reporting!

Please upgrade to v1.1.0 if not already done.
If that doesn't help, please share some screenshots of each scenario you described.

Best,
AK

**Comment by syswombat** [comment]
this is OK with time ![graphite-time-settings12h](https://user-images.githubusercontent.com/3279451/43803432-22d5ec98-9a99-11e8-96f6-2efeeae52556.PNG)

this is not OK with Date/Time
![graphite-time-settings](https://user-images.githubusercontent.com/3279451/43803473-372969f4-9a99-11e8-8f62-58f00d8e06d9.PNG)

and how to do a safe update?

**Comment by dnsmichi** [comment]
As already said on the [forums](https://monitoring-portal.org/t/graphite-show-more-24-00-and-nothing-over-a-1-day/3388), this is not this module but a different one.

```
graphite	0.0.0.5
```

does not follow this module's version history. Probably you're using https://github.com/findmypast/icingaweb2-module-graphite and should create an issue over there.
