### ISSUE TITLE
graphite default template is not catching all values

### ISSUE THREAD

**Issue by eichlerla2** [Icinga/icingaweb2-module-graphite#178]
## Expected Behavior
Graphite converts dots (".") in the perf values of a check to an slash. 

Perfdata
```
/usr/lib/nagios/plugins/check_disk -w 15% -c 10% -l -X tmpfs -X devtmpfs -X proc -X sysfs -X udev -X devpts
DISK OK - free space: / 5255 MB (54% inode=90%); /boot 411 MB (90% inode=99%); /opt/mysql.abc 40102 MB (41% inode=99%); /opt/mysql.def 28598 MB (18% inode=99%);| /=4312MB;8567;9071;0;10079 /boot=42MB;406;430;0;478 /opt/mysql.abc=55571MB;85674;90713;0;100793 /opt/mysql.def=122657MB;135444;143412;0;159347
```
is stored by graphite as

```
disk_dynamic # tree 
    └── perfdata
        ├── _
        │   ├── crit.wsp
        │   ├── max.wsp
        │   ├── value.wsp
        │   └── warn.wsp
        ├── _boot
        │   ├── crit.wsp
        │   ├── max.wsp
        │   ├── value.wsp
        │   └── warn.wsp
        ├── _dev
        │   └── value.wsp
        └── _opt_mysql
            ├── abc
            │   ├── crit.wsp
            │   ├── max.wsp
            │   ├── value.wsp
            │   └── warn.wsp
            └── def
                ├── crit.wsp
                ├── max.wsp
                ├── value.wsp
                └── warn.wsp
```

So some perf values are stored in subfolders below the normal folder. The default template should also catch the values in subfolders.

## Current Behavior
Graphs from values in subfolders are not shown in icingaweb2.

## Possible Solution
Graphs in subfolders should also shown. Maybe if metrics_filters value $perfdata$ is able to catch everything between perfdata and value.

```
[default-service.metrics_filters]
value = "$service_name_template$.perfdata.$perfdata$.value"
```

## Steps to Reproduce (for bugs)
1. mount a filesystem with a dot in the mountpoint name
2. configure a disk service based on check_disk in icinga2
3. run this configuration -> let collect icinga2 perfdata of this service
4. check shown graphs in icingaweb2

## Your Environment
* Module version (System - About):  1.0.1
* Icinga Web 2 version and modules (System - About):  monitoring 2.6.0, grpahite 1.0.1
* Icinga 2 version (`icinga2 --version`): r2.9.1-1
* Graphite (carbon, web, whisper) version: 0.9.15 
* Operating System and version: Debian GNU/Linux 8.11 (jessie)
* Webserver, PHP versions: apache2 2.4.10-10+deb8u12, php5 5.6.36+dfsg-0+deb8u1

**Comment by Al2Klimov** [comment]
As discussed w/ @bobapple (offline):

This may be an Icinga 2 issue (`s/./_/`).
