### ISSUE TITLE
More flexible use of variables in templates

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-graphite#18]
I would like to be more flexible with variables in templates.

Already somehow working example (gives me the all value as one line in a graph, but filter fails as it only provides complete value like kpi_aosm_all_la_cmd):
```
title = KPI AOSM LA $la
filter = $icingaService.smsc-kpis.perfdata.kpi_aosm_all_la_$la
areaMode = stacked
areaAlpha = 0.6
lineWidth = 0

value : color=green, alias AOSM
```

What I really would need (should give me the ok and fail value as two stacked lines in a graph):
```
title = KPI AOSM LA $la
filter = $icingaService.smsc-kpis.perfdata
areaMode = stacked
areaAlpha = 0.6
lineWidth = 0

kpi_aosm_ok_la_$la.value : color=green, alias AOSM-OK
kpi_aosm_fail_la_$la.value : color=read, alias AOSM-Fail
```

**Comment by Al2Klimov** [comment]
Closing this in favor of #54.
