### ISSUE TITLE
Graphite module shows thresholds incorrectly

### ISSUE THREAD

**Issue by ghost** [Icinga/icingaweb2-module-graphite#182]
1. `/etc/icinga2/features_available/graphite.conf` contains this - `enable_send_thresholds = true`
2. Icinga2 is sending thresholds to Graphite:
```
tcpdump -i lo port 2003 -A | grep postgres_database_size
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes

icinga2.my_db_host.services.postgres_database_size.nrpe.perfdata.Database_1.crit 107374182400 1534133576
icinga2.my_db_host.services.postgres_database_size.nrpe.perfdata.Database_1.warn 85899345920 1534133576
icinga2.my_db_host.services.postgres_database_size.nrpe.perfdata.Database_2.value 20590092804 1534133576
icinga2.my_db_host.services.postgres_database_size.nrpe.perfdata.Database_2.crit 107374182400 1534133576
icinga2.my_db_host.services.postgres_database_size.nrpe.perfdata.Database_2.warn 85899345920 1534133576
icinga2.my_db_host.services.postgres_database_size.nrpe.perfdata.Database_3.value 857563652 1534133576
icinga2.my_db_host.services.postgres_database_size.nrpe.perfdata.Database_3.crit 107374182400 1534133576
icinga2.my_db_host.services.postgres_database_size.nrpe.perfdata.Database_3.warn 85899345920 1534133576
icinga2.my_db_host.services.postgres_database_size.nrpe.perfdata.Database_4.value 170811908 1534133576
icinga2.my_db_host.services.postgres_database_size.nrpe.perfdata.Database_4.crit 107374182400 1534133576
icinga2.my_db_host.services.postgres_database_size.nrpe.perfdata.Database_4.warn 85899345920 1534133576
```
My template is expected to display graphs of the current database size with thresholds:
```
[postgres_database_size.graph]
check_command = "postgres_database_size"


[postgres_database_size.urlparams]
title = "$perfdata_lable$"
areaAlpha = "0.5"
lineWidth = "2"
lineMode = "connected"
yMin = "0"
yUnitSystem = "binary"

[postgres_database_size.metrics_filters]
warn.value = "$service_name_template$.perfdata.$perfdata_lable$.warn"
crit.value = "$service_name_template$.perfdata.$perfdata_lable$.crit"
db.value = "$service_name_template$.perfdata.$perfdata_lable$.value"

[postgres_database_size.functions]
warn.value = "alias(color($metric$, '#f49842'), 'DB warn')"
crit.value = "alias(color($metric$, '#ff0000'), 'DB crit')"
db.value = "alias(color($metric$, '#649ffc'), 'DB size')"
```

## Expected Behavior
Graphs, drawing 3 lines per database - current size, warning and critical thresholds.

## Current Behavior
Depends on the template:
If I use the template I provided - I get this error:
`Undefined index: icinga2.my_db_host.services.postgres_database_size.nrpe.perfdata.Database_1.warn`

If I remove `crit.value` from filters and functions - it works but doesn't show ALL databases, just some of them. Here, on a screenshot you can see that Icinga checks 9 DBs but only 4 graphs are shown. (Sorry, I had to remove DB names - it's a security policy)

![graphs](https://user-images.githubusercontent.com/15808276/44012790-e794d606-9f04-11e8-9f10-7f4a63ac011c.jpg)

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
Copy my template, adjust to your data, see the problem.

## Context
We can't see thresholds on graphs, although that is useful

## Your Environment
* Module version (System - About): 1.1.0
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): r2.9.1-1
* Graphite (carbon, web, whisper) version: 0.9.15
* Operating System and version: Centos 7.5
* Webserver, PHP versions: nginx 1.14.0-1 and rh-php71-fpm  backend for Icinga, gunicorn 18.0 for Graphite.

**Comment by Al2Klimov** [comment]
Hello @alexizmailov and thank you for reporting!

Are there all of your three desired metrics for all of your databases in Graphite itself?

Best,
AK
