### ISSUE TITLE
Make dummy images cacheable

### ISSUE THREAD

**Issue by hekeli** [Icinga/icingaweb2-module-graphite#185]
Please make requests to /icingaweb2/graphite/graph-dummy/ cacheable by browser.

Add some Expires header a day or week forward, remove cachebuster, set Cache-Control: public, etc.

It's wasting lots of server resources for a "dummy" purpose of serving the same silly empty png. Especially when there are dozens of graphs for a service.

Probably the URL for this could be stripped completely static so it doesn't matter what host/service you are looking, the same cached png can be used?

**Comment by hekeli** [comment]
Well I tried following the code and messing with removing cachebuster etc, but it's too much for me to handle. If dummy is cached, seems it won't try refresh the images at all etc.

Basically my problem is one or two people leaving browser open with a service having dozens of images. Reloading all the images every 10 seconds makes terrible load even on 4 core server. Atleast I found $this->setAutorefreshInterval(10) so I can raise the hardcoded value to something sane. Of course it would be nice to have a way to change refresh time for the images only.

Also the "Show More" images button seems kind of redundant, since _all_ the images are loaded even if they are not shown initially.

**Comment by hekeli** [comment]
Also after the clients session expires, I'm still seeing request after request for the graph images which simply get some redirect response.

/icingaweb2/authentication/login?redirect=graphite%2Fgraph%2Fservice....

How about stopping the requests if not logged in?

**Comment by Al2Klimov** [comment]
Hello @hekeli and thank you for reporting!

Please test #198.

Best,
AK

**Comment by hekeli** [comment]
@Al2Klimov Works ok here, on top of my personal patch, reduces dummy http queries nicely.

Though I would still clean up all the unnecessary cachebuster code as I have did and leave all timestamping to client side:

e.attr("src", src.replace(/\&r=\d+/, '') + '&r=' + (new Date()).getTime());
