### ISSUE TITLE
No graph displayed (Error 500)

### ISSUE THREAD

**Issue by PhilJung** [Icinga/icingaweb2-module-graphite#186]
Debian 9 + debian packaged icinga2 / icingaweb2 packets
+ icingaweb2-module-graphite cloned from github (because this module is not available in debian packages)

graphite-api seems ok as I can curl it and get a meaningfull answer.

When looking in Firefox debugger, under network part, I see this

```
SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8mb4', query was: SELECT ss.check_command AS service_check_command, scv_check_command.varvalue AS _service_check_command FROM icinga_objects AS so
INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id AND so.is_active = 1 AND so.objecttype_id = 2
INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = s.host_object_id
INNER JOIN icinga_servicestatus AS ss ON ss.service_object_id = so.object_id
LEFT JOIN icinga_customvariablestatus AS scv_check_command ON s.service_object_id = scv_check_command.object_id AND scv_check_command.varname = 'check_command' COLLATE latin1_general_ci WHERE (so.name1 = 'XXXXXXXXXXXX' AND so.name2 = 'disk') ORDER BY s.display_name COLLATE latin1_general_ci ASC LIMIT 1
```

Original request: 
```
http://monitoring.rd/icingaweb2/graphite/graph/service?host.name=XXXXXXXXXXXXXX&service.name=disk&service.check_command=disk&disk=_&template=disk&start=-3600&end=&width=350&height=200&cachebuster=100723442512308&legend=1&r=1536918641160
```

**Comment by PhilJung** [comment]
Workaround: force database character set to utf8mb4 in application configuration, database tab

**Comment by Al2Klimov** [comment]
@lippserd That's an Icinga Web 2 problem, right?

**Comment by Kimmax** [comment]
It is a Icinga Web 2 problem of some sort and it also was being discussed in another module, not sure where it's going to go from there: https://github.com/Icinga/icingaweb2-module-cube/issues/7
Maybe adding it to the docs as a _gotcha_ helps, I ran into the same issue today

**Comment by lippserd** [comment]
The solution was already posted. You have to set the appropriate character set in the database resource configuration.
