### ISSUE TITLE
Graph metrics collected, but no line on graph

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2-module-graphite#188]
## Expected Behavior
Metric collected should be drawn on graph.

## Current Behavior
Metric collected, but no line is plotted:
```
https://icingahost:8484/icingaweb2/monitoring/list/services?host=host.domain.com#!/icingaweb2/monitoring/service/show?host=host.domain.com&service=hive-2.1-end-user-query-check-prod&graph_range=10800&graph_debug=1

Graphs assembling process record
+ Icinga check command: 'hive-2.1-end-user-check-ssl-sqlline'
+ Obscured check command: NULL
+ Applying templates for check command 'hive-2.1-end-user-check-ssl-sqlline'
+ Applying default templates, excluding previously used metrics
++ Not applying template 'default-host'
++ Applying template 'default-service'
+++ Fetched 1 metric(s) from 'http://icinga-prod-graphite-01:443/metrics/expand?query=icinga2.host.domain.com.services.hive-2_1-end-user-query-check-prod.hive-2_1-end-user-check-ssl-sqlline.perfdata.%2A.value'
+++ Excluded 0 metric(s)
+++ Combined 1 metric(s) to 1 chart(s)
```

## Steps to Reproduce (for bugs)
I recently cloned the Docker volume to use a new name, but debug information suggests previous data is there, but not sure why the graph line is not showing.

## Context
Cannot view lineage of issue visually.

## Your Environment
Name	Version
--------------------------------
director	master
doc	2.6.1
graphite	1.1.0
monitoring	2.6.1
setup	2.6.1

**Comment by Al2Klimov** [comment]
Hello @mtdeguzis and thank you for reporting!

Please share a screenshot of the detail view showing your problem.

Best,
AK

**Comment by mtdeguzis** [comment]
No longer an issue in this sense. I get data now, but I can't filter beyond 6 hours.
