### ISSUE TITLE
Configuration Guide missing and a little mistake

### ISSUE THREAD

**Issue by Fiiti** [Icinga/icingaweb2-module-graphite#19]
Hi Thomas,
I wonder, how I can read more about the configuration terms?
 [Like this fork](https://github.com/findmypast/icingaweb2-module-graphite )

Also is it possible to use the _storage-schemas.conf_  like the fork above? So I can use more time sections?
____________________________________
The lillte mistake in your Read.me:

> Edit /etc/icingaweb2/modules/graphite/config.ini and set **web\\_url** to the Graphite web host.

should read as web_url , didn't it?

**BTW:**
should the settings
`[graphite] web_url = http://my.graphite.web`
not written with the used port `[graphite] web_url = http://my.graphite.web:2003` ?

Best regards,
Fiiti

**Comment by dnsmichi** [comment]
FYI: That findmypast community module isn't a fork of this one, but actually a custom implementation based on the PNP module.

**Comment by Fiiti** [comment]
Ahh, okay- my failure. And what about the commands? Is there a guide anywhere?

**Comment by dgoetz** [comment]
You can configure storage-schemas as you like, but keep in mind your check intervals for doing so.

And yes, you can add a port to the URL, but 2003 indicates you want to try to directly connect to graphite, but this module uses graphite web as interface, so typically port 80 or 443 which is default for http/https is fine.

**Comment by Fiiti** [comment]
Thanks. 
BTW: I corrected in my first entry the mistake at web\_url. It wasn't right shown, because i used BOLD Tags and the wrong backslash.

**Comment by Al2Klimov** [comment]
@Fiiti Since 777204d the module may be configured over the web UI so you don't have to deal with any ini files or backslashes.

"should read as web_url , didn't it?" – No, because _ is part of the markdown syntax.
