### ISSUE TITLE
Graph two hours behind current time

### ISSUE THREAD

**Issue by teclogi** [Icinga/icingaweb2-module-graphite#190]
The graph displayed is 2 hours behind the current time.
The graph in the graphite-web dashboard is showing the right time.

## Expected Behavior

The graph should be till the current local time.

## Current Behavior

The graph displayed is 2 hours behind the current time.
Also the current values will be displayed in 2 hours.
When the screenshots where taken, the local time of the server and the client was 11:45 PM CET.

Time line 2 hours behind:
![2018-11-05 11_49_16-icinga web](https://user-images.githubusercontent.com/27726999/47997956-e8b00e80-e0fd-11e8-8374-88316f463998.png)

Time line ok:
![2018-11-05 11_47_07-graphite browser](https://user-images.githubusercontent.com/27726999/47997971-f2397680-e0fd-11e8-82e0-4a7f7303943d.png)

## Your Environment

* Module version (System - About): 1.1.0
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): r2.9.1-1
* Graphite (carbon, web, whisper) version: graphite-carbon 0.9.15-1, python-whisper 0.9.15-1, graphite-web 0.9.12+debian-6
* Operating System and version: Debian 9
* Webserver, PHP versions:

**Comment by teclogi** [comment]
It seems to have something to do with the browser localisation in Icingaweb2.
Location is Europe/Berlin but the auto detection is showing "Browser (Europe/London)" woth Google Chrome  (Version 70.0.3538.77).

In Firefox, Edge and Internet Explorer the timezone is Europe/Paris.

**Comment by log1-c** [comment]
In case you haven't updated already: IcingaWeb2 2.6.2 fixes the wrong time zone detection: https://icinga.com/2018/11/22/icinga-web-2-6-2-bugfix-release/

**Comment by Al2Klimov** [comment]
Hello @teclogi and thank you for reporting!

Please tell in which browsers the bug occurrs.

Best,
AK

**Comment by teclogi** [comment]
Hi AK,

as previously written, only Google Chrome was affected.

> It seems to have something to do with the browser localisation in Icingaweb2.
> Location is Europe/Berlin but the auto detection is showing "Browser (Europe/London)" woth Google Chrome (Version 70.0.3538.77).
> 
> In Firefox, Edge and Internet Explorer the timezone is Europe/Paris.

This problem seems to be fixed since the update to icingaweb2 2.6.2.

Best regards,
Tim

**Comment by Al2Klimov** [comment]
Fixed – closed.
