### ISSUE TITLE
Optimize detailview and requests against Graphite

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2-module-graphite#192]
## Expected Behavior

The Detail view should be displayed as fast as possible. 

## Current Behavior

For Example icmp: we can see that the module is doing one request per metric and after that it is requesting all the metrics with one query. For there are unessacary requests done, just to get some metric names. Imagine a "slow" (answering a request in 1 second) graphite-web server here - it will take 5 seconds just for the names . The other issue is that we can wait "forever" for the detail view if the server is slower.

```
+ Icinga check command: 'icmp'
+ Obscured check command: NULL
+ Applying templates for check command 'icmp'
++ Applying template 'icmp-rt'
+++ Fetched 1 metric(s) from 'http://127.0.0.1:8080/metrics/expand?query=icinga2.myhost.host.icmp.300.perfdata.rtmin.value'
+++ Fetched 1 metric(s) from 'http://127.0.0.1:8080/metrics/expand?query=icinga2.myhost.host.icmp.300.perfdata.rta.value'
+++ Fetched 1 metric(s) from 'http://127.0.0.1:8080/metrics/expand?query=icinga2.myhost.host.icmp.300.perfdata.rtmax.value'
+++ Excluded 0 metric(s)
+++ Combined 3 metric(s) to 1 chart(s)
++ Applying template 'icmp-pl'
+++ Fetched 1 metric(s) from 'http://127.0.0.1:8080/metrics/expand?query=icinga2.myhost.host.icmp.300.perfdata.pl.value'
+++ Excluded 0 metric(s)
+++ Combined 1 metric(s) to 1 chart(s)
+ Applying default templates, excluding previously used metrics
++ Applying template 'default-host'
+++ Fetched 4 metric(s) from 'http://127.0.0.1:8080/metrics/expand?query=icinga2.myhost.host.icmp.300.perfdata.%2A.value'
+++ Excluded 4 metric(s)
+++ Combined 0 metric(s) to 0 chart(s)
++ Not applying template 'default-service'
```

## Possible Solution

Make the detail view independent from fetching the metrics.

**Comment by Al2Klimov** [comment]
@bobapple Is this a realistic response time for a real-world Graphite Web server?

**Comment by bobapple** [comment]
It highly depends on the  graphite installation. If that server is not capable to answer an request within one seconds, then I'd reconsider my hardware configuration. 

Anyways, I think it makes sense to load the graphs independently from the rest of the detailview.

**Comment by hekeli** [comment]
Agree, I was just wondering why my logs are full of identical metrics queries. I was looking for doing some caching, but as the requests seem to originate internally it's not possible with the web server, so any caching would need to be internal. For now I optimized my graphite setup running it directly from uwsgi daemon.

**Comment by Al2Klimov** [comment]
@bobapple I don't think that it's a good idea as you want to see changes immediately. (Don't you?) If someone really hits some load limit by a large setup, they'll either reconsider the hardware configuration or put a caching proxy between IW2 and Graphite.

@cstegm Does the detail view actually load slowly or are you "just wondering why my logs are full of identical metrics queries" like @hekeli?

**Comment by nilmerg** [comment]
Fetching is now independent.
