### ISSUE TITLE
Automatic reloading of the column makes selection of custom time range hard to use

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-graphite#193]
## Expected Behavior
During automatic reload of the page date-time-picker should always stay open and responsive also on slow systems or no autorefresh should happen when date-time-picker is open.

## Current Behavior
When trying to select a custom time range, the date-time-picker closes and reopens when the graph reappears (or sometime only closes or hangs somewhere in the open space). This makes it hard to use especially on slow systems where after reload of the page it takes some time until the graph is displayed.

## Steps to Reproduce (for bugs)
1. Open a service view with a graph
2. Try to select a custom timerange (and have a slow system or be slow with picking the timerange)
3. Autorefresh happens and closes the date-time-picker
4. Date-time-picker reappears when graph is displayed

## Context
Internal customers want to analyze a graph for a specific timeperiod when a problem occurred.

## Your Environment
* Module version (System - About): 1.1.0
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): 2.10.2
* Graphite (carbon, web, whisper) version: 0.9.16
* Operating System and version: RHEL 7.6
* Webserver, PHP versions: Apache Httpd + PHP-FPM 7.1

**Comment by Al2Klimov** [comment]
IMO an issue of Icinga Web 2 itself.
