### ISSUE TITLE
[Feature Request] : Allow setting the background color

### ISSUE THREAD

**Issue by Farfaday** [Icinga/icingaweb2-module-graphite#204]
Hi,
We should have the possibility to set the background colour of the graph to match the theme currently in use.
See https://graphite.readthedocs.io/en/latest/render_api.html#bgcolor
Thanks!
François

**Comment by dnsmichi** [comment]
You can do so already within the templates, either per command or on a global basis. Look for `urlparams`.

https://icinga.com/docs/graphite/latest/doc/04-Templates/

Cheers,
Michael

**Comment by Farfaday** [comment]
Thank you ! That answered my request!
