### ISSUE TITLE
Sporadically get Error 500 in Logs while loading Graphs

### ISSUE THREAD

**Issue by Stefomat** [Icinga/icingaweb2-module-graphite#205]
Hi all,

i have a problem with my installation of icingaweb2-module-graphite.

## Expected Behavior

Graphs loading, without producing errors in the log.

## Current Behavior

Graphs load almost completely fine.
The readings are all there, as well in the "Graphite" menu as in the Host and Service Details. Only issue is, that if the time ist set to show only the last 5 minutes of data, the logs get fludded with error 500 (although the graph still shows all the readings).
Maybe important: The 5 minutes match my intervall of icinga pushing new perfdata to carbon cache.
```
127.0.0.1 - - [18/Mar/2019:15:31:28 +0100] "POST /render?from=1552919188&until=1552919488&width=1815&height=220&hideLegend=&tz=Europe%2FParis&_salt=1552919488.000&vTitle=Percent&lineMode=connected&drawNullAsZero=false&graphType=line&majorGridLineColor=%230000003F&minorGridLineColor=%2300000000&_ext=whatever.svg&areaAlpha=0.5&areaMode=all&lineWidth=2&min=0&yUnitSystem=none&target=alias%28color%28scale%28fqdn.secret-hostname_de.services.DNS.dns.perfdata.time.value%2C%201000%29%2C%20%27%231a7dd7%27%29%2C%20%27Response%20time%20%28ms%29%27%29 HTTP/1.1" 500 1719 "-" "icingaweb2-module-graphite"
```

## Steps to Reproduce (for bugs)

1. enable carbon-cache with storage-schemas.conf for icinga2

/etc/carbon/storage-schemas.conf:
```
[icinga2_perfdata]
pattern = ^icinga2\..*\.perfdata\.
retentions = 5m:2d,20m:10d,60m:90d,360m:4y
```
2. install graphite-api (debian package)

/etc/graphite-api.yaml:
```
search_index: /var/lib/graphite-api/index
whisper:
  directories:
    - /var/lib/graphite/whisper
time_zone: Europe/Berlin
carbon:
  hosts:
    - 127.0.0.1:7002
  retry_delay: 15
  carbon_prefix: carbon
  replication_factor: 1
```
3. install icingaweb2-module-graphite

/etc/icingaweb2/modules/graphite/config.ini:
```
[graphite]
url = "http://127.0.0.1:8013"
insecure = "1"

[ui]
default_time_range = "1"
default_time_range_unit = "hours"
disable_no_graphs_found = "0"
```
4. Select a service and set time to show to 5 minutes (or the time corresponding to your check interval)

## Context

It doesn't effect endusers, just looking at the webfrontend. But receiving all the logs and knowing there has to be something wrong bothers me.

i'm happy to provide more info if needed.

Thanks

## Your Environment

* Module version (System - About): graphite 1.1.0
* Icinga Web 2 version and modules (System - About): icingaweb2 2.6.2, businessprocess 2.2.0, director 1.6.1, ipl v0.1.1, monitoring 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.3-1
* Graphite (carbon, web, whisper) version: debian package for graphite-carbon (0.9.15-1), graphite-api (1.1.3-2+deb9u1)
* Operating System and version: GNU/Linux Debian 9.8 amd64
* Webserver, PHP versions: apache2 2.4.25-3+deb9u6, libapache2-mod-wsgi-py3 (4.5.11-1)  for graphite-api, php7.0 7.0.33-0+deb9u3

**Comment by Al2Klimov** [comment]
I'm afraid this works as expected as of #143.
