### ISSUE TITLE
Extra "blank" graph area

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2-module-graphite#209]
## Expected Behavior
Only the clone_time metric graph should show, which used to.

## Current Behavior
The actual graph is second, the first is seemingly blank.

![image](https://user-images.githubusercontent.com/27829577/57697669-c7d2f380-7621-11e9-96f0-4cb947b5a821.png)

Graphs assembling process record

```
+ Icinga check command: 'check-github'
+ Obscured check command: NULL
+ Applying templates for check command 'check-github'
+ Applying default templates, excluding previously used metrics
++ Not applying template 'default-host'
++ Applying template 'default-service'
+++ Fetched 3 metric(s) from 'http://icinga-prod-graphite-01:443/metrics/expand?query=icinga2.myicinga_domain_com.services.check_github.check-github.perfdata.%2A.value'
+++ Excluded 0 metric(s)
+++ Combined 3 metric(s) to 3 chart(s)
```

## Possible Solution
?

## Steps to Reproduce (for bugs)
Install the below script:
https://gist.github.com/mtdeguzis/8749545c3a767107916ad8551cde270c

Invocation via Icingaweb2:
```
'/usr/lib64/nagios/plugins/check-github' '-p' 'https' '-r' 'apache/flume'
```

## Context
Have to click "more" under blank graph

## Your Environment

* Module version (System - About): 1.1.0
* Icinga Web 2 version and modules (System - About): 2.6.3
* Icinga 2 version (`icinga2 --version`): r2.10.4-1
* Graphite (carbon, web, whisper) version:  ? not sure which command to use
* Operating System and version: RHEL 7.4
* Webserver, PHP versions: 
```
# /opt/rh/rh-php71/root/usr/sbin/php-fpm --version
PHP 7.1.8 (fpm-fcgi) (built: Aug  8 2017 09:02:40)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by Al2Klimov** [comment]
Hello @mtdeguzis and thank you for reporting!

Please share the recursively expanded Graphite web tree of your service. I.e.:

![Bildschirmfoto 2019-08-13 um 12 13 28-](https://user-images.githubusercontent.com/6053266/62934331-960a2e00-bdc4-11e9-89b0-1c0e9b18d437.png)

Best,
AK
