### ISSUE TITLE
new version doesnt check if perfdata is enabled or not

### ISSUE THREAD

**Issue by jelayeb** [Icinga/icingaweb2-module-graphite#21]
i just updated to newer version 0005 and i got some issues with services that enable_perfata is set to false, but graphite module is trying always to show the graph, which breaks the view 
and get this error  

`#0 /usr/share/icingaweb2/modules/graphite/library/Graphite/Macro.php(68): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Trying to get p...', '/usr/share/icin...', 68, Array)
#1 /usr/share/icingaweb2/modules/graphite/library/Graphite/Macro.php(36): Icinga\Module\Graphite\Macro::resolveMacro('address', Array)
#2 /usr/share/icingaweb2/modules/graphite/library/Graphite/Grapher.php(123): Icinga\Module\Graphite\Macro::resolveMacros('icinga2.$addres...', Array, false, true, true)
#3 /usr/share/icingaweb2/modules/graphite/library/Graphite/Grapher.php(191): Icinga\Module\Graphite\Grapher->getPreviewImage(NULL, Object(Icinga\Module\Monitoring\Object\Service), 'pc_1')
#4 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/show/components/grapher.phtml(2): Icinga\Module\Graphite\Grapher->getPreviewHtml(Object(Icinga\Module\Monitoring\Object\Service))
#5 /usr/share/php/Icinga/Web/View.php(231): include('zend.view:///us...')
#6 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#7 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/partials/object/detail-content.phtml(3): Zend_View_Abstract->render('show/components...')
#8 /usr/share/php/Icinga/Web/View.php(231): include('zend.view:///us...')
#9 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#10 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/service/show.phtml(8): Zend_View_Abstract->render('partials/object...')
#11 /usr/share/php/Icinga/Web/View.php(231): include('zend.view:///us...')
#12 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render('service/show.ph...')
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('service/show.ph...', NULL)
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#18 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction')
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#21 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#22 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#23 {main}`

restore the older version 0004 solved my issue, which makes it clear it is the new version issue but nothing else. 

Thanks 
Jasem

**Comment by dnsmichi** [comment]
What exactly do you mean by `version 0004` and `version 0005`?

**Comment by jelayeb** [comment]
when i check System > About > Loaded modules i can see graphite version is 0.0.0.4 which is the one works fine. 
and when i use the new version i see 0.0.0.5 which cause the problem.

**Comment by Al2Klimov** [comment]
@jelayeb Has your problem been fixed w/ 777204d?

**Comment by bobapple** [comment]
Closing this due to lacking feedback
