### ISSUE TITLE
Error 500 to rendering graphics on graphite with icingaweb2 in "check_network" query.

### ISSUE THREAD

**Issue by cristorrian** [Icinga/icingaweb2-module-graphite#211]
### Issue and Steps to Reproduce

Install nsclient on Windows server 2016 and configure command on icingaweb2 to monitoring network.

### PLEASE PROVIDE COMMAND HERE

check_network

### Details

* NSClient++ version: 0.5.2.39
* OS and Version: Windows Server 2016
* Checking from: Icingaweb2 with graphite
* Checking with: CheckSystem module with "check_network" query

### Additional Details

Metrics of network are good, but graphite isn't rendering graphics correctly.

### Images

Graphics.

![imagen](https://user-images.githubusercontent.com/51986864/60650990-88689c80-9e45-11e9-93f2-4ab5dc41ac65.png)

Performance Data

![imagen](https://user-images.githubusercontent.com/51986864/60651216-0af15c00-9e46-11e9-9e7f-968c8b370ac2.png)

Others queries like "check_memory" or "check_cpu" render graphics perfectly.

Any idea??

**Comment by Al2Klimov** [comment]
@dnsmichi What about https://github.com/Icinga/icinga2/pull/7346 ?

**Comment by dnsmichi** [comment]
I'm not really sure what you mean. What's the error coming from graphite resp. the stored performance data?

**Comment by Al2Klimov** [comment]
Look at the screenshot's bottom. There are some broken characters.

**Comment by dnsmichi** [comment]
Ah, localized schrott. AFAIK nscp-local allows to override the perf-syntax for Graphite, same as with the cpu performance counter. 

https://docs.nsclient.org/reference/windows/CheckSystem/#check_network

-> `perf-syntax`

This is explained here in detail too: https://www.netways.de/blog/2016/04/14/windows-performance-counters-with-nsclient-and-graphite/

Not sure how the service is configured (or how the check command looks like), but this should be fairly easy to override.

**Comment by Al2Klimov** [comment]
I meant: Shouldn't we merge that PR to avoid such problems?

**Comment by Al2Klimov** [comment]
Hello @cristorrian and thank you for reporting!

Please either test @dnsmichi's solution or wait for https://github.com/Icinga/icinga2/pull/7346 to be merged (won't be included in v2.11) and report whether/how your problem has been solved.

Best,
AK

**Comment by dnsmichi** [comment]
Hi @cristorrian snapshot packages have been built for Windows, can you give them a whirl?
