### ISSUE TITLE
Provide Graph without Auth

### ISSUE THREAD

**Issue by pboehm89** [Icinga/icingaweb2-module-graphite#213]
Hello Guys,

we want to share our live graphs via URL on different websites. In the newest version it is only possible to view the Graphs if you are logged in into icingaweb2.

Is there any Workaround to share the graphs without Authentification?

Thanks for any help.

**Comment by Al2Klimov** [comment]
Hello @pboehm89!

I'm afraid there isn't any workaround, not for this module as such.

You'd have to fake basic auth inside a reverse proxy in front of Icinga Web or similar.

Best,
AK
