### ISSUE TITLE
Special Characters in perfdata label do result in "No such graph" 

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-graphite#214]
## Expected Behavior

Graphs for perfdata label containing :: , $, #  are rendered.

## Current Behavior

Graphs for perfdata label containing :: , $, #  are not rendered.

## Steps to Reproduce (for bugs)

1. Use CheckCommand "check_interface"
2. Enable snmpd , create dummy interface with Special character
3. Whisper files are written, but no graph is shown

## Context

See the steps to reproduce, this example was brought to our attention by a Customer.

## Your Environment

* Module version (System - About): Version 1.1.0
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): 2.8.4
* Graphite (carbon, web, whisper) version: from 1.1.0 up to 1.1.5

## Screenshots

![Screenshot](https://user-images.githubusercontent.com/7203835/61952526-5b2a8c80-afb4-11e9-9f36-5396b66da241.png)
![Screenshot1](https://user-images.githubusercontent.com/7203835/61952534-641b5e00-afb4-11e9-8d2d-a04e45ac7199.png)

## Additional Context

ref/NC/624675

**Comment by log1-c** [comment]
At least for :: I can't confirm this, as I have graphs with perfata labels containing those:
![image](https://user-images.githubusercontent.com/24474580/62352421-64fa4580-b508-11e9-8e9f-4e7b5445c0cd.png)

maybe try to update your graphite module to the current master by doing a "git pull" or just delete the graphite folder from /usr/share/icingaweb2/module and git clone it again. There were some fixes to the perfdata label parsing recently.

What I also did was create a template for those checks, as the perfdata label is not compatible to the default.
I also offered them for a pull request some time ago: https://github.com/Icinga/icingaweb2-module-graphite/pull/208/commits/7e5da0bdf48f4c51d946a2610e8a55c65bd6a492

Check there to maybe get some inspiration for your check :)

**Comment by dnsmichi** [comment]
`::` is a check_multi label where Icinga replaces this with a `.` to allow multiple levels (this is documented [here](https://icinga.com/docs/icinga2/latest/doc/14-features/#graphite-schema)). The graphite module doesn't know about this conversion and doesn't handle multiple values value the `.value` entry.

**Comment by Al2Klimov** [comment]
`$` works (master), `#` fixed just now and `::` has been explained by @dnsmichi.

**Comment by mkayontour** [comment]
can confirm it works on the master :)
