### ISSUE TITLE
Beautify timespan picker layout

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingaweb2-module-graphite#215]
The timespan picker design should be adapted for our forms redesign. The layout should be optimised for narrower layouts.

This is how it looks now
![Artboard](https://user-images.githubusercontent.com/6977434/62694933-96c24f00-b9d5-11e9-94f2-aca90700cc99.jpg)

We can do this better
![Artboard Copy](https://user-images.githubusercontent.com/6977434/62694950-9d50c680-b9d5-11e9-8c38-1f6f8033b83a.jpg)

**Comment by Al2Klimov** [comment]
Did you perform changes locally to create the second screenshot? If yes, what about a PR?

**Comment by Al2Klimov** [comment]
No, it's a mockup.
