### ISSUE TITLE
Need help understanding where URI Encoding happens

### ISSUE THREAD

**Issue by 6d6178** [Icinga/icingaweb2-module-graphite#219]
Hi, 
I'm currently trying to use carbonapi (and maybe even metrictank) as backend for this module. I already figured out how to replace the expand url with a find. Now I'm struggling with the render URI. The URI is encoded at some point to this pattern: `render?from=1567412279\u0026until=1567415879\u0026width=1112.22\u0026height=220\u0026`
carbonapi wants an `&` though, so this doesn't work. I already searched the code for the place where the encoding (decoding?) happens, but I can't find it. Can anyone help me out?
The URI is built in `library/Graphite/Web/Widget/GraphImage.php` and then does a request, but there is no mention of en/decoding.
Of course I plan to make a Pull Request once it works.

**Comment by yoshi314** [comment]
i am also interested in this, since switching to carbinapi i have different urls than what module makes.

**Comment by nilmerg** [comment]
I'm not aware of any encoding the module does here. `&` is the default parameter separator.
