### ISSUE TITLE
Non SSL Connection to graphite broken

### ISSUE THREAD

**Issue by benhartwich** [Icinga/icingaweb2-module-graphite#222]
Hi,

I´m using graphite on an ubuntu 18.04 vm (internal network) and I connected Icinga2 with graphite with latest version of the icinga2web-graphite-module. I´ve configured the backend address to the local vm ip address. When I open a service or host graphite tells me: 

`Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER'`

What I´m doing wrong?
Php 7.2 is used and apache2.

**Comment by dnsmichi** [comment]
Are you sure that php-curl is installed and loaded?

**Comment by benhartwich** [comment]
I think so:

```
php -version
PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies

php -info | grep curl
/etc/php/7.2/cli/conf.d/20-curl.ini,
curl
```

Is there a way to check phpinfo in icingaweb2?

**Comment by teclogi** [comment]
@benhartwich 
I have the same problem.
How did you resolve this problem?

**Comment by benhartwich** [comment]
@teclogi I enabled php7.2 at apache, which had the correct php libs (php-curl was not installed with version 7.0).
