### ISSUE TITLE
Dealing with performance data, if not all got critical or warning thresholds

### ISSUE THREAD

**Issue by milohb** [Icinga/icingaweb2-module-graphite#224]
I use my plugin to monitor a lot of services. It generates perfomance data, which is fed to graphite-web. For some of the metrics I us warning and/or critical thresholds (on some metrics they don't make sense in my scenario).

Graphite module can't render this in an sensible way: Depending on which metric filters I use, I get graphs without thresholds, not all graphs or errors.

## Expected Behavior
All graphs are rendered, independent of the order of metric filters. If no warning or critical data is available for a given graph, don't render that threshold (or render with 0)

## Current Behavior
I made this matrix:

metric | warn | crit | t1 | t2 | t3 | t4 | t5 | t6 
-------|-------|---|----|---|----|---|---|----
A | 0 | 0 | s | e | n | e | n | e
B | X | 0 | s | e | s | e | n | e
C | 0 | X | s | e | n | e | s | e
D | X | X | s | e | s | e | s | e

wich means: 
A-D are the metrics, A without thresholds, B only warning, D both

t1 to t6 are different templates:
- t1 only value in metric_filters
- t2 metric_filters: value before warn
- t3 metric_filters: warn before value
- t4 metric_filters: value before warn
- t5 metric_filters: warn before value
- t6 value, warn and crit in metric_filters

results:
- s: graph is shown 
- n: graph is not shown
- e: error (Undefined index: icinga2[...].value)

By now the only way to see all graphs is using a template without thresholds, but I would like to see them.

## Possible Solution
Maybe a workaround could be, to use an own template for every metric (I used the $perfdata$ macro), but that would be inflexible on changes: I use director for icinga, but to change templates I have to edit the ini files.

## Steps to Reproduce (for bugs)
Add a service and add only few thresholds as above.

## Context
I'm monitoring a realtime exchange platform for traffic data.

## Your Environment

* Module version (System - About): graphite 1.1.0 (no change on master)
* Icinga Web 2 version and modules (System - About): 2.7.1 with director 1.6.2, graphite, monitoring, translation
* Icinga 2 version (`icinga2 --version`): 2.11.0
* Graphite (carbon, web, whisper) version: 1.1.5
* Operating System and version: debian jessie (8.11)
* Webserver, PHP versions: apache 2.4, php 5.6.40

**Comment by sukhwinder33445** [comment]
Hi @milohb ,

**Comment by milohb** [comment]
Hi,

thanks for looking into this old issue.

I had the problems when mixing different metrics in one graph while some, but not all metrics have thresholds.

But I can't reproduce this any more, so it might be gone by some update in between.

I'm closing this for now.
