### ISSUE TITLE
Metrics excluded from graph

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2-module-graphite#226]
## Expected Behavior
Metrics are combined to graph for basic ping4 in Icinga

## Current Behavior
Debug of graph:
```
+ Icinga check command: 'ping4'
+ Obscured check command: NULL
+ Applying templates for check command 'ping4'
++ Not applying template 'ping-rta'
++ Not applying template 'ping-pl'
+ Applying default templates, excluding previously used metrics
++ Applying template 'default-host'
+++ Fetched 2 metric(s) from 'http://icinga-dev-graphite-01/metrics/expand?query=icinga2.host_domain_com.host.ping4.perfdata.%2A.value'
+++ Excluded 2 metric(s)
+++ Combined 0 metric(s) to 0 chart(s)
++ Not applying template 'default-service'
````

Metrics for this host:
![image](https://user-images.githubusercontent.com/27829577/69356537-9df22d80-0c51-11ea-9e1c-2f98ab6fcaa8.png)
![image](https://user-images.githubusercontent.com/27829577/69355857-85cdde80-0c50-11ea-992b-9c3bc4a5ecb9.png)
```
/ # whisper-fetch  / # whisper-fetch  /opt/graphite/storage/whisper/icinga2/host_domain_com/host/ping4/perfdata/rta/value.wsp  | grep -v None
1574352180      0.000227
1574352480      0.000205
1574352780      0.000213
```

## Context
How do I troubleshoot this exclusion? I'm not sure what to do after combing through the stdout logs.
```
21/11/2019 16:08:47 :: [listener] MetricLineReceiver connection with 127.0.0.1:43816 established
21/11/2019 16:08:47 :: [listener] MetricLineReceiver connection with 127.0.0.1:43816 closed cleanly
21/11/2019 16:08:52 :: [tagdb] Tagging icinga2.host_domain_com.host.ping4.perfdata.pl.warn
21/11/2019 16:08:52 :: [tagdb] Tagged icinga2.host_domain_com.host.ping4.perfdata.pl.warn in 0.00622868537902832
21/11/2019 16:08:57 :: [listener] MetricLineReceiver connection with 127.0.0.1:43852 established
21/11/2019 16:08:57 :: [listener] MetricLineReceiver connection with 127.0.0.1:43852 closed cleanly
```

## Your Environment

* Module version (System - About):
```
1.1.0
cb2a94397529f5a4b73d423fe89fabf2b0f064a6
Icinga Graphite moduleThis module integrates an existing Graphite installation in your Icinga Web 2 frontend.
monitoring
graphite/debug: Allow debugging directly via the web UI
```
* Icinga Web 2 version and modules (System - About):
![image](https://user-images.githubusercontent.com/27829577/69355240-7732f780-0c4f-11ea-9ee5-24eeae575c91.png)
* Graphite (carbon, web, whisper) version: not sure how to get this, using docker.io/graphiteapp/graphite-statsd latest tag.
* Operating System and version: RHEL 7.8
* Webserver, PHP versions: 
```
/opt/rh/rh-php71/root/usr/sbin/php-fpm -v
PHP 7.1.30 (fpm-fcgi) (built: Jul 10 2019 09:46:42)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by mtdeguzis** [comment]
Could this be due to it's a host and the template is skipped?
```
Config preview: Standard Linux Server
```
zones.d/director-global/host_templates.conf
template Host "Standard Linux Server" {
    check_command = "ping4"
}
```

**Comment by log1-c** [comment]
Try copying the default ping template and changed it so that it becomes a `ping-host` template.
Did this for the icmp command/template. You will need a new variable in icinga2 to obscure the check command and let the graphite module know about it:
https://github.com/Icinga/icingaweb2-module-graphite/pull/208/files#diff-b5b7ce8f3617c8c675bce3fbca0e09f5
https://github.com/Icinga/icingaweb2-module-graphite/pull/208

**Comment by mtdeguzis** [comment]
Looks good now, thanks for the reply.
