### ISSUE TITLE
Not showing graphs for hosts/services with unicode characters

### ISSUE THREAD

**Issue by vlatko-va** [Icinga/icingaweb2-module-graphite#230]
Looks like it is an issue in Graphite, I can see the service names displayed properly in the web GUI on port 800 but no subfolders in the tree are available.

Debugging in Icingaweb2 shows a query where non-latin chars are replaced with underscores:

http://IP:8000/metrics/expand?query=icinga2.meteo.services.__________-_____________.check__number.perfdata.%2A.value 

## Possible Solution

Works when the service name is with latin chars and then use display_name with Unicode chars as a workaround

apply Service "Only Latin chars here" {
  display_name = "Unicode is welcome"

Maybe just update the Troubleshooting page with a note for this possible issues

**Comment by sukhwinder33445** [comment]
This is a Graphite issue.
