### ISSUE TITLE
Templates are not applied to custom check commands

### ISSUE THREAD

**Issue by ozzi-** [Icinga/icingaweb2-module-graphite#231]
When defining a custom ini template for a command defined in commands.conf, the template is not applied.

## Expected Behavior
Creating file called "/usr/share/icingaweb2/modules/graphite/templates/snmpv3.ini" with the following content:
```
[snmpv3.graph]
check_command="check-snmpv3"

[snmpv3.urlparams]
bgcolor=red
```
The background color in the graph should be red

## Current Behavior
URL params are not transmitted to graphite (nor any other config in the template).
See the following screenshot including debug output
![alt text](https://i.imgur.com/D2jGaVJ.png)

When I edit default.ini and add bgcolor=red, it works.
When I edit as an example hostalive.ini and add the bgcolor it works too, since "hostalive" is not a custom command.

## Possible Solution
I debugged Graphite/Graphing/Templates.php and assured that the custom ini template is actually loaded and the urlparam was parsed. However Graphite/Web/Widget/Graphs.php does not seem to find the template.

## Steps to Reproduce (for bugs)
1. Define a custom command (or use an existing one) , here "yourcommand"
2. Create a file called /usr/share/icingaweb2/modules/graphite/templates/yourcommand.ini
```
[yourcommand.graph]
check_command="yourcommand"

[yourcommand.urlparams]
bgcolor=red
```
3. Check if graphs have a red background

## Context
I would like to have custom graphs for my custom commands.

## Your Environment
* Module version (System - About):     2.6.2 and 2.7.3 tested
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.4-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 18.04.2 LTS (Bionic Beaver)
  Kernel: Linux
  Kernel version: 4.15.0-65-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 7.3.0
  Build host: b2ecadfb68ab

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
* Graphite (carbon, web, whisper) version: 1.1.0
* Operating System and version: Ubuntu Server 18.04
* Webserver, PHP versions: Apache 2 + PHP 7.2

**Comment by dnsmichi** [comment]
Putting the template into `/etc/icingaweb2/modules/graphite/templates/snmpv3.ini` doesn't help?

**Comment by ozzi-** [comment]
Hi Michi
Unfortunately, this does not help either.. 
![alt text](https://i.imgur.com/3243Ynl.png)
I don't think it is per se the wrong place to put the ini files, since when editing ini files under /usr/share/icingaweb2/modules/graphite/templates/ that have the check_command directive to a command that is not "custom" defined, they are used properly.

**Comment by ozzi-** [comment]
Hi @dnsmichi  
While further debugging using the PHP methods, I found the problem:
https://github.com/Icinga/icingaweb2-module-graphite/blob/master/library/Graphite/Graphing/Templates.php#L265
```php 
 $templates[$templateName] = empty($curves) ? null : (new Template())
       ->setCurves($curves)
       ->setUrlParams($urlParams);
```
Since my templates did not set any curve options, as in was missing the "metrics_filters" section, the template was loaded, parsed but then nulled by this code snippet above.

Adding this to the template, fixed resulted in the template being applied:
```
[check-snmpv3.metrics_filters]
value = "$host_name_template$.perfdata.$perfdata$.value"
```

In the documentation (https://icinga.com/docs/graphite/latest/doc/04-Templates/#templates-structure-metric-filters) it says the following :
```
Define what metric to use and how many curves to display in the resulting graph. Each option’s key represents the name of a curve. Its value the path to the metric in Icinga 2’s graphite naming schema. If no metrics are given, no graphs are rendered.
```
The graphs are rendered, but the template is ignored, this behaviour should be changed or the documentation adapted to state, that the 'metrics_filters' is required.
