### ISSUE TITLE
Almost unusable timepicker

### ISSUE THREAD

**Issue by pboguslawski** [Icinga/icingaweb2-module-graphite#232]
Hello,

(1)

Using timepicker from icigna2-module-graphite (checked latest commit c6e5fc739aa308b2d616c6bfc912e5661a70fae4 also) to select custom graph period is almost impossible with icingaweb2 2.6.2-3~bpo9+1 from debian stretch-backports; picker popup disappears randomly (probably on icigaweb2 background refreshes?) and one cannot enter dates/hours to finish period picking.

Seems that using mouse causes things worse than using keyboard to enter data in picker. Checked in latest Firefox ESR and Chromium.

(2)
Would be nice to have feature to select time period using mouse on graph; there is such thing in 

http://docs.pnp4nagios.org/

and its extremely useful (just select interesting part of graph to zoom it quickly without picker hassle).

Regards,
Paweł

**Comment by knorx** [comment]
Jesus - and I always thought our setup was somehow broken. A workaround would also be to deliberately disable reloads when the date picker is selected, if this is an issue.
