### ISSUE TITLE
PDF Export - "Image not found or type unknown"

### ISSUE THREAD

**Issue by m4k5ym** [Icinga/icingaweb2-module-graphite#239]
## Expected Behavior

PDF Report which contains actual graphite-graphs

## Current Behavior

Blanks with message "Image not found or type unknown"

## Possible Solution

Not in sight.

## Steps to Reproduce (for bugs)

1. Click on Graphite
2. Click on Host
3. Click on Arrow down
4. Click on PDF
5. Open the PDF

## Context

Can't create reports for boss.

## Your Environment

* Module version (System - About): 1.10
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`): 2.11.3
* Graphite (carbon-c-relay, go-carbon, graphite-web) version: 2.6, 0.14.0, 1.1.7 
* Operating System and version: CentOS 7.7.1908
* Webserver, PHP versions: 2.4.6, rh-7.1

**Comment by Al2Klimov** [comment]
Hello @m4k5ym and thank you for reporting!

* Are you using the built-in PDF export or https://github.com/Icinga/icingaweb2-module-pdfexport ?
* Do you export _a particular host_ or the _host list_?
* Do you have the same problem with services?

Best,
AK

**Comment by m4k5ym** [comment]
Hi,

- Customer switched to pdfexport module. Now it looks prettier but still no graphs included.
- Just the first page of hosts from graphite module.
- Didn't tested yet.

Sincerly,
Maksym

**Comment by m4k5ym** [comment]
Hello @Al2Klimov

Will something happen here or should I consider this feature as „non-functional“ and close this issue?

If it is the wrong project for this issue please be so kind and move it to the correct project.

Sincerly,
Maksym

**Comment by Al2Klimov** [comment]
> Will something happen here

Counter question:

> * Didn't tested yet.

Will something happen **here**?

**Comment by m4k5ym** [comment]
No I can’t and won’t test it since it is a customer of yours company which I‘m not working for anymore.

And to be hones this problem also have been mentioned by an Icinga Community Forum member where I also referenced on this particular issue with no further answer nor action...

https://community.icinga.com/t/graphite-graphs-bot-displaying-on-pdf-export/4306

I‘m out by now. I‘m not joining this ball pushing game where I just waste my time by testing non successful solutions where I also have to proof multiple times that it is really not working.

Just pull the repo yourself and configure it with your provided manuals and let me know if it worked. I‘m tried a lot and wouldn’t have created an issue if it would work as expected.

**Comment by m4k5ym** [comment]
Due no further answer. Guess it? Closed!
