### ISSUE TITLE
Graphite Web : Unable to fetch metric(s)

### ISSUE THREAD

**Issue by KhanHam** [Icinga/icingaweb2-module-graphite#243]
Hi,
I have a graphite module running on the server with icinga2 and another server hosting graphite web which is deployed using docker.
But I am unable to fetch the metrics.
This is the debug log
```
+ Icinga check command: 'http'
+ Obscured check command: NULL
+ Applying templates for check command 'http'
++ Not applying template 'response-size'
++ Not applying template 'response-time'
+ Applying default templates, excluding previously used metrics
++ Applying template 'default-host'
+++ Fetched 0 metric(s) from 'http://graphite/metrics/expand?query=icinga2.somename.com.host.http.perfdata.%2A.value'
+++ Excluded 0 metric(s)
+++ Combined 0 metric(s) to 0 chart(s)
++ Not applying template 'default-service'
```

## Expected Behavior
 Icinga should be displaying graphs on its web interface.

## Current Behavior
 Graphite -> Services -> "No graphs found" message is displayed

## Your Environment

* Module version (System - About):
* Icinga Web 2 version and modules (System - About): 2.8.0-rc1
* Icinga 2 version (`icinga2 --version`): r2.11.2-1
* Graphite (carbon, web, whisper) version: 1.1.4
* Operating System and version: Ubuntu 16.04.6 (Graphite-Web)
                                                     Debian 9.12 (Icinga)

**Comment by nilmerg** [comment]
Hi, this looks to me like a configuration issue. Please head over to our [forums](https://community.icinga.com/c/visualization/11) and describe your issue there. There are more people around which may be of help. Thank you.

**Comment by RUDI-TERROR** [comment]
try delete all spaces in Host- and Servicename
