### ISSUE TITLE
Graph not displayed

### ISSUE THREAD

**Issue by R00T88** [Icinga/icingaweb2-module-graphite#25]
when i try to display a graph on my icinga2 installation i got this message:

```
file_get_contents(http://192.168.0.102/metrics/expand?query=icinga2.Icinga2.services.ping4.disk.perfdata.*): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'file_get_conten...', '/usr/share/icin...', 61, Array)
#1 /usr/share/icingaweb2/modules/graphite/library/Graphite/GraphiteWeb.php(61): file_get_contents('http://192.168....')
#2 /usr/share/icingaweb2/modules/graphite/library/Graphite/GraphiteQuery.php(143): Icinga\Module\Graphite\GraphiteWeb->listMetrics('icinga2.Icinga2...')
#3 /usr/share/icingaweb2/modules/graphite/library/Graphite/GraphiteQuery.php(121): Icinga\Module\Graphite\GraphiteQuery->listMetrics()
#4 /usr/share/icingaweb2/modules/graphite/application/controllers/ShowController.php(257): Icinga\Module\Graphite\GraphiteQuery->getWrappedImageLinks(Object(Icinga\Module\Graphite\GraphTemplate), Array)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Graphite\Controllers\ShowController->serviceAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('serviceAction')
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#11 {main}
```

What can cause this?

**Comment by lazyfrosch** [comment]
Have you tried accessing the URL in a browser? Does Graphite Web work?

    http://192.168.0.102/metrics/expand?query=icinga2.Icinga2.services.ping4.disk.perfdata.*

**Comment by R00T88** [comment]
It's not accessible

Not Found

The requested URL /metrics/expand was not found on this server.

**Comment by lazyfrosch** [comment]
Then Graphite Web is not working, or under a different location.

**Comment by R00T88** [comment]
How can i check if settings are correct?

**Comment by Al2Klimov** [comment]
"Fixed" – closed

**Comment by michealp43** [comment]
even i m getting same error

#0 /usr/share/icingaweb2/modules/graphite/library/Graphite/Grapher.php(127): Icinga\Module\Graphite\Grapher->inlineImage(String)
#1 /usr/share/icingaweb2/modules/graphite/library/Graphite/Grapher.php(191): Icinga\Module\Graphite\Grapher->getPreviewImage(NULL, Object(Icinga\Module\Monitoring\Object\Service), String)
#2 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/show/components/grapher.phtml(2): Icinga\Module\Graphite\Grapher->getPreviewHtml(Object(Icinga\Module\Monitoring\Object\Service))
#3 /usr/share/php/Icinga/Web/View.php(270): include(String)
#4 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#5 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/partials/object/detail-content.phtml(3): Zend_View_Abstract->render(NULL)
#6 /usr/share/php/Icinga/Web/View.php(270): include(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#8 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/service/show.phtml(8): Zend_View_Abstract->render(NULL)
#9 /usr/share/php/Icinga/Web/View.php(270): include(String)
#10 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#16 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/Web.php(409): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#20 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#21 {main}

**Comment by michealp43** [comment]
Please let me out
