### ISSUE TITLE
Horizontal Time Axis Layout not adjustable too much info stuffed into axis space 

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-graphite#253]
If you have enough collected data over a longer time period the horizontal time axis below the graphs gets too crowded and non destinguishable unreadable. This needs adjustment or at least the possibility to set font size or viewable timeframe maybe the ability to scroll horizontally ? 

## Expected Behavior
Even longer time periods should be horizontally readable, or at least scrollable and maybe the font size is adjustable.

## Current Behavior
Longer Timeperiods in a frame don't scale well and the horizontal axis is overflown with information which is not adjustable.

## Possible Solution
Module adjustments to scale down the timeframe or at least make font size and the frame horizontal axis scrollable

## Steps to Reproduce (for bugs)
Collect enough data over a longer period, and take a look.

![Screenshot1](https://user-images.githubusercontent.com/7203835/112953068-706a9d80-913d-11eb-850f-15df8a63574a.jpg)

## Your Environment
* Module version (System - About):
bayerisch            1.0.0
businessprocess              2.3.0
ca           1.0.3
director               master
elasticsearch     1.0.0
fileshipper          1.2.0
fraenkisch          1.0.0
graphite              1.1.0
incubator            0.6.0
ipl           v0.5.0
logicalparent     0.0.1
monitoring         2.8.2
oesterreichisch 1.0.0
reactbundle       0.8.0
shks       2.2.2
vspheredb         1.1.0
* Icinga Web 2 version and modules (System - About): 
2.8.2
Git commit
8a89839af94a247ee2149b2336c73b8251b477c0
* Icinga 2 version (`icinga2 --version`): 
Icinga2 Version 2.12.2-1 on RHEL7
* Operating System and version:
RHEL7
* Webserver, PHP versions:
PHP RH 7.3.11

Tested on the following Browser Versions:

![image001](https://user-images.githubusercontent.com/7203835/112953882-27671900-913e-11eb-9de8-55a6421bf819.png)
![image002](https://user-images.githubusercontent.com/7203835/112953887-27ffaf80-913e-11eb-9cd8-d4e896008695.png)

ref/NC/705361

**Comment by nilmerg** [comment]
Graphs use full width in detail areas now.
