### ISSUE TITLE
Image reloads in background keep running unnecessarily

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2-module-graphite#254]
Once visiting any of the overviews (hosts, services) the module starts to continuously reload the graphs in the background. Even when leaving the overviews and switching to a view where not a single graph is shown.

Is there any reason for this? Or is this just an oversight and can be disabled?

**Comment by Al2Klimov** [comment]
> Even when (...) switching to a view where not a single graph is shown.

How can graph reloading happen when there aren’t any graphs?

**Comment by nilmerg** [comment]
There's JS that reloads all ever registered images every 8 seconds. (https://github.com/Icinga/icingaweb2-module-graphite/blob/master/public/js/module.js#L26-L66)
