### ISSUE TITLE
How to change the time settings of icinga web 2

### ISSUE THREAD

**Issue by maurox521** [Icinga/icingaweb2-module-graphite#257]
How can I change the time configuration of icinga 2 web, it turns out that the connection and disconnection times of the devices that I monitor appear one hour apart, for example if a device actually connected at 4:00 p.m., in icinga web2 It appears to me that it connected at 5:00 p.m. I tried to change the time zone in sudo nano /etc/php/7.3/apache2/php.ini and reset apache 2 but nothing happens

**Comment by nilmerg** [comment]
You should change this in your user preferences of Icinga Web 2.
