### ISSUE TITLE
Graphite does not work without icingadb anymore

### ISSUE THREAD

**Issue by Virsacer** [Icinga/icingaweb2-module-graphite#269]
Navigating to any host or service gives

    Trait "Icinga\Module\Icingadb\Common\Macros" not found

    #0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
    #1 {main}

## Your Environment
* Module version (System - About): 2915e4a4d2bf1e5bc72bdd967862f8e010ff49b6 https://github.com/Icinga/icingaweb2-module-graphite/pull/259
* Icinga Web 2 version and modules (System - About): 2.9.5
* Icinga 2 version (`icinga2 --version`): r2.13.2-1
* Operating System and version: Ubuntu 21.10
* Webserver, PHP versions: PHP 8.0.8

**Comment by nilmerg** [comment]
Ouch, thanks for testing/reporting!

**Comment by Virsacer** [comment]
> Ouch, thanks for testing/reporting!

Thanks for fixing ;-)
