### ISSUE TITLE
Display Graph in Detailview 

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingaweb2-module-graphite#27]
Each host and service should display the graph in its detailview. The action link "Graphite" should be removed.

**Comment by lazyfrosch** [comment]
Just to clarify: Grapher and Detailview are two separate extensions :wink:

We should prefer Grapher here.

**Comment by Thomas-Gelf** [comment]
Just for the records, the main motivation for originally implementing it as a link was that Graphite tends to be slow as hell in large environments. Image loading itself is of course deferred, but the problem is looking up things in it's painfully slow index - even with databases. Please consider allowing users to opt out of this via a config setting.

**Comment by lazyfrosch** [comment]
We can use asynchronous loading of the details:

```
<div class="container" data-last-update="-1" data-icinga-url="%s" data-icinga-refresh="60">
```

Similar to https://github.com/Icinga/icingaweb2-module-eventdb/blob/master/library/Eventdb/ProvidedHook/Monitoring/DetailviewExtension.php#L58

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: sure, that would help. But then that's Detailview, not Grapher. Wasn't available at the time being, but absolutely makes sense here. We should be able to ship something similar with no flickering in our next IcingaDB/ipl-based iteration of the monitoring module.

**Comment by lazyfrosch** [comment]
@Thomas-Gelf `getPreviewHtml` should be able to put out the required HTML, `data-icinga-url` is implemented globally.

The module would only need to provide the action Endpoint to actually load the content from...

Only downside with Grapher is, that only one Graphing hook works.

**Comment by Thomas-Gelf** [comment]
Correct!

**Comment by Al2Klimov** [comment]
@bobapple I'm not ready with the detail view yet, but feel free to check out the above changes we discussed offline.
