### ISSUE TITLE
Too many Graphs are shown

### ISSUE THREAD

**Issue by BT-Danny** [Icinga/icingaweb2-module-graphite#277]
## Expected Behavior
Usually if there are more than two Graphs, it will show a expansion button "Show more" or "Show Less"

## Current Behavior
The Button is rendered as a Checkbox with "Show MoreShow Less"

## Possible Solution
No Solution found. I checked the config.ini and the graphTemplates.conf but didn't find anything which could cause this Issue

## Steps to Reproduce (for bugs)
1. Open a Service with more than two Graph Metrics
2. Scroll down to the Graphs

## Context
The Problem causes too many Graphs for example in Service "Icinga", which has a lot of Metrics. Our Users need to scroll down for a long time

## Your Environment
* Module version (System - About):
* Icinga Web 2 version and modules 2.11.0
* Icinga 2 version (`icinga2 --version`): r2.13.4-1
* Graphite (carbon, web, whisper) version: 1.1.0
* Operating System and version: CentOS 7 centos-release-7-9.2009.1.el7.centos.x86_64
* Webserver, PHP versions: Apache 2, PHP 8.0

![image](https://user-images.githubusercontent.com/104197378/177513925-f3b9173e-126e-40b8-8328-194e58000d86.png)

**Comment by nilmerg** [comment]
There is no `Show More` or `Show Less` anymore. You seem to use an outdated version of the module. Please upgrade to latest.

**Comment by BT-Danny** [comment]
Thats weird, I installed v 1.1.0, which seems to be the latest version according to your changelog

**Comment by nilmerg** [comment]
That's not maintained it seems. Take a look at the release page: https://github.com/Icinga/icingaweb2-module-graphite/releases

**Comment by BT-Danny** [comment]
Thanks a lot. I'll install it as soon as possible. I never updated a module before, since I'm pretty new to Icinga. I just found a tutorial how to update icinga director. Is it similar in this module?

**Comment by nilmerg** [comment]
The general approach is usually:

* Wipe the old installation (keep config though, but that's stored separately anyway)
* Consult the upgrading documentation if there's any, update the config if necessary
* Install the new version

**Comment by BT-Danny** [comment]
It worked perfectly fine, thanks a lot:

I'm just struggeling with the default Template for the Graphs. In the beginning the background has been black, which I changed in graphTenplate.conf, but we want the graphs to be filled blue instead of the vertical bars. Do you have a pro tip where I can find the correct Configline?

![image](https://user-images.githubusercontent.com/104197378/177574128-12de2086-ad5c-428f-85cd-6038ed00c16f.png)

**Comment by nilmerg** [comment]
These are defined by the templates, in the `templates` directory of the module installation.

**Comment by BT-Danny** [comment]
Thanks, I'll give it a shot. I'll mark this thread as soled. Thanks a lot for your help

**Comment by BT-Danny** [comment]
By the way, I solved the Issue on our Host. If anybody encounters the same Problem:
I deleted the old Whisper Databases, because they kept the old metrics. After that it looks like I want it:
![image](https://user-images.githubusercontent.com/104197378/177989409-f022f97e-8307-4094-8fb4-c473dc15e86e.png)
