### ISSUE TITLE
Remove demo Dockerfile

### ISSUE THREAD

**Issue by lippserd** [Icinga/icingaweb2-module-graphite#287]

**Comment by Al2Klimov** [comment]
Please consider keeping. It's a pretty convenient tool to show all theoretically possible graphs at once. Useful for developing/reviewing, e.g. #199.

**Comment by lippserd** [comment]
I have no problem with having such an option, but not here. If it is useful for development, it should be included in our Docker dev setup. For the documentation readers, there should be screenshots showing the different templates.

**Comment by Al2Klimov** [comment]
Even better! Can we postpone this until (a) docker dev env does the things Dockerfile.demo does atm?

**Comment by lippserd** [comment]
No, because there is a release coming up.

**Comment by lippserd** [comment]
See #288.
