### ISSUE TITLE
Enabling graphite module crashes Icingaweb completely

### ISSUE THREAD

**Issue by maniackatzentier** [Icinga/icingaweb2-module-graphite#297]
Hi,
I try to install the icingaweb2 graphite-module.
Icinga, Icingaweb and Graphite for itself are running fine. Icinga is able to send data to Graphite, which I can see in the Graphite Web Interface.
As soon as I execute `icingacli module enable graphite` or enable the module in icingaweb, my whole Icingaweb- website gets broken with the following errors:

`Fatal error: Uncaught Error: Call to undefined method Icinga\Application\Modules\Module::registerHook() in /usr/share/icingaweb2/modules/graphite/run.php:3 Stack trace: #0 /usr/share/php/Icinga/Application/Modules/Module.php(1370): include() #1 /usr/share/php/Icinga/Application/Modules/Module.php(1357): Icinga\Application\Modules\Module->includeScript() #2 /usr/share/php/Icinga/Application/Modules/Module.php(441): Icinga\Application\Modules\Module->launchRunScript() #3 /usr/share/php/Icinga/Application/Modules/Manager.php(233): Icinga\Application\Modules\Module->register() #4 /usr/share/php/Icinga/Application/Modules/Manager.php(191): Icinga\Application\Modules\Manager->loadModule() #5 /usr/share/php/Icinga/Application/ApplicationBootstrap.php(483): Icinga\Application\Modules\Manager->loadEnabledModules() #6 /usr/share/php/Icinga/Application/Web.php(97): Icinga\Application\ApplicationBootstrap->loadEnabledModules() #7 /usr/share/php/Icinga/Application/ApplicationBootstrap.php(416): Icinga\Application\Web->bootstrap() #8 / in /usr/share/icingaweb2/modules/graphite/run.php on line 3`

It's a Debian 11 system.
Version Information from icingacli:
`icingacli version
Icinga Web 2  2.11.4   
Git Commit    11453bfa92a70a44efbf7f966f5e7f27e9300a28 
PHP Version   7.4.33    
MODULE      VERSION   
monitoring  2.11.4    
`

**Comment by nilmerg** [comment]
Please upgrade the module to the latest version.

**Comment by maniackatzentier** [comment]
Thank you, that led me in the right direction. I somehow cloned an old fork of the repo. Cloning the original repo did the trick.
