### ISSUE TITLE
Broken graphs with php 8.2

### ISSUE THREAD

**Issue by BastienDurel** [Icinga/icingaweb2-module-graphite#301]
After upgrading to PHP 8.2 (debian 12 default), graphs are broken (invalid data)

Each image generated has text prepended :

```
Deprecated:  Creation of dynamic property Icinga\Module\Graphite\Controllers\MonitoringGraphController::$backend is deprecated in /usr/share/icingaweb2/modules/graphite/library/Graphite/Web/Controller/MonitoringAwareController.php on line 47
```

Declaring the $backen property resolves the warning, and therefore corrects the images.

```
diff --git a/library/Graphite/Web/Controller/MonitoringAwareController.php b/library/Graphite/Web/Controller/MonitoringAwareController.php
index dca2ebd..59caa80 100644
--- a/library/Graphite/Web/Controller/MonitoringAwareController.php
+++ b/library/Graphite/Web/Controller/MonitoringAwareController.php
@@ -21,6 +21,7 @@ abstract class MonitoringAwareController extends Controller
 {
     /** @var bool Whether to use icingadb as the backend */
     protected $useIcingadbAsBackend = false;
+    protected $backend = null;
 
     /**
      * Restrict the given monitored object query for the currently authenticated user
```

## Your Environment
* Module version (System - About):	1.2.2
* Icinga Web 2 version and modules (System - About): 2.11.4
  * icinga/icinga-php-library	0.10.1
  * icinga/icinga-php-thirdparty	0.11.0
  * monitoring	2.11.4
* Icinga 2 version (`icinga2 --version`): r2.13.7-1
* Operating System and version: Debian 12
* Webserver, PHP versions: apache 2, PHP 8.2.7

**Comment by nilmerg** [comment]
Will be fixed in the upcoming release.
