### ISSUE TITLE
Support compact and image URL

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-graphite#46]
## Expected Behavior
For integration in other tools I would like to have a compact URL for integration via iframe and image URL for integration as img. One example would be hover templates in NagVis.

## Current Behavior
Compact view does not remove controls, graph URL only works with internal parameters like the template.

## Possible Solution
For compact view changing host view like this would be possible:
```
<?php if (! $this->compact): ?>
<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->hostname ?></h1>
</div>
<?php endif ?>
```

For image URL I have no idea if it would require a additional view or changing the graph URL to also work only with host and service parameter is possible.

**Comment by Al2Klimov** [comment]
@dgoetz Things have changed since 6490db1 – see https://youtu.be/rG14P-wtubM

**Comment by Al2Klimov** [comment]
Does that fit your needs?

**Comment by dgoetz** [comment]
Compact fits the needs were iframe is available, also having an url usable for img so getting the rendered image directly would be helpful as not everywhere it is possible to embed html (e.g. jasperreports).

**Comment by Al2Klimov** [comment]
@dgoetz

"You can use the Graphite Web itself (w/o our module) to embed images in jasperreports."

– @bobapple

**Comment by Al2Klimov** [comment]
Fine. I'll implement this. But only because #11 requires a re-design of the /show/graph HTTP interface (which is... far from being production-ready right now).
