### ISSUE TITLE
[dev.icinga.com #11824] icingaweg2-module-graphite feature request

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-graphite#6]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11824

**Created by p0nts on 2016-05-21 08:55:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-05-21 09:28:34 +00:00 (in Redmine)_

---

​I am wondering if it is possible to show all graphs at once with either one of the graphite web plugins?

​
findmypast/icingaweb2-module-graphite
​
Icinga/icingaweb2-module-graphite

I would prefer using the icinga module, and show all graph's of the server as soon as you click the "Action Graphite" button, did anyone manage this? So instead of clicking the link for each service or host, just click once wherever you want at the host/service and get a list of all connected graphs for that server?​
​

**Comment by Al2Klimov** [comment]
Things have changed since 6490db1 – see https://youtu.be/rG14P-wtubM
