### ISSUE TITLE
[dev.icinga.com #11927] Show All Graphs + Time Range

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-graphite#7]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11927

**Created by p0nts on 2016-06-10 13:48:31 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-08 10:50:09 +00:00 (in Redmine)_

---

I would love to have the feature to show all graph's of the server as soon as you click the "Action Graphite" button, or create a seperation action button with a link towards all its host graphs.

So instead of clicking the link for each service or host, just click once wherever you want at the host/service and get a list of all connected graphs for that server?

Motivation:
Whenever one of our servers is down, we would like to have a graph overview of the whole server to pinpoint if we can find anything in the graph's. For now it is to much work going to every service and check their graphs

------------------------------------------------------------------------

Would also love to see a possibility to select certain default time windows for the graphs, instead of a graph of the last hour it would be awesome to have several possible time windows such as a few hours, a day and a few days.

**Comment by Al2Klimov** [comment]
Things have changed since 6490db1 – see https://youtu.be/rG14P-wtubM
