### ISSUE TITLE
[dev.icinga.com #12103] Action_Url Description

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-graphite#8]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12103

**Created by quentinv on 2016-07-05 15:39:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-09 16:45:12 +00:00 (in Redmine)_

---

Hello,

I would like to know if it's possible to change the name of the action url (default **action 1**, see screenshot). For example I want to change "action 1" by "graphite".

I already saw someone who changed it.

Thank you

**Attachments**

* [action.JPG](https://dev.icinga.com/attachments/download/3492/action.JPG) quentinv - _2016-07-05 15:38:34 +00:00_

**Comment by Al2Klimov** [comment]
This has already been fixed another way.
