### ISSUE TITLE
Limit amount of labels on the x-axis

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2-module-graphite#82]
Graphite currently chooses the amount of labels on the x-axis to be displayed by itself. This may cause, especially on long time ranges, the labels to overlap.

There is a function called `find_x_times` in file `graphite/render/glyph.py` which is responsible for these labels. The function accepts a `labelUnit` and `labelStep` and calculates the amount of labels based on the requested time range.

Making this configurable may allow to control the amount of x-axis labels in a more predictable way. (e.g. for a three year time range passing *one day* as `labelUnit` and *365* as `labelStep` causes graphite to display a label on the x-axis every 31536000 seconds => 1 year)

**Comment by nilmerg** [comment]
One could of course also pass *one year* as `labelUnit` and *1* as `labelStep`, but that'd need to be supported by `find_x_times` first..

**Comment by Al2Klimov** [comment]
It seems someone [has already fixed](https://github.com/graphite-project/graphite-web/blame/d053e1fd73376ed544b1cc8cc2178f2b089142cb/webapp/graphite/render/glyph.py#L113) this in upstream.
