### ISSUE TITLE
Graph images don't load - A non-numeric value encountered

### ISSUE THREAD

**Issue by Wuestengecko** [Icinga/icingaweb2-module-graphite#86]
Graph images fail to load, resulting in an empty display section.

## Expected Behavior
Graphs should load correctly.

## Current Behavior
Nothing shows up (neither a graph, nor the text "No graphs found", nor an error message). Opening the image URL (via the Firefox developer tools) reveals the following error:
```
A non-numeric value encountered
#0 /usr/share/webapps/icingaweb2/modules/graphite/library/Graphite/Graphing/Chart.php(134): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'A non-numeric v...', '/usr/share/weba...', 134, Array)
#1 /usr/share/webapps/icingaweb2/modules/graphite/application/controllers/GraphController.php(115): Icinga\Module\Graphite\Graphing\Chart->serveImage(Object(Icinga\Web\Response))
#2 /usr/share/webapps/icingaweb2/modules/graphite/application/controllers/GraphController.php(79): Icinga\Module\Graphite\Controllers\GraphController->supplyImage('apt')
#3 /usr/share/webapps/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Graphite\Controllers\GraphController->serviceAction()
#4 /usr/share/webapps/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('serviceAction')
#5 /usr/share/webapps/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/webapps/icingaweb2/library/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/webapps/icingaweb2/library/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/webapps/icingaweb2/public/index.php(4): require_once('/usr/share/weba...')
#9 {main}
```

## Possible Solution
The break happened in commit d633c10. The line producing the error is the following:

    $timeSpan = ($this->until === null ? time() : $this->until) - $this->from - 30;

The issue can be worked around by casting the `until` and `from` references to integers first, like this:

    $timeSpan = ($this->until === null ? time() : (int)$this->until) - (int)$this->from - 30;

The root cause seems to be that somehow the suffix (s for seconds) ends up being in the `from` field, which is later used as-is in the formula above.

## Steps to Reproduce (for bugs)
This started happening on a previously-working installation when the mentioned commit was merged into master. Reverting the commit makes the graphs work again.

## Context
I read about breaking changes within PHP 7.1 concerning calculations with non-numeric or partially numeric strings (i.e. starting with a numeric value, but with some kind of non-numeric suffix). The latter is supposed to produce a "Notice" - which it does when testing short sample code in the CLI -, but for some reason it escalates to an error in the Icingaweb2 environment (not in a short test php script on that server).

## Your Environment
* Module version (System - About): r225.ga6c2b2d
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): 2.7.2
* Operating System and version: Arch Linux
* Webserver, PHP versions: Apache 2.4.29 w/ PHP 7.1.11

Note that I install the module via a self-created system package (that's where the module version string comes from), however it does not make a difference concerning this issue.

**Comment by Al2Klimov** [comment]
Hello @Wuestengecko and thank you for your report.

Does the above commit fix your problem?

**Comment by nilmerg** [comment]
Just encountered the same error. Mentioned fix fixed it. Thanks.

**Comment by Wuestengecko** [comment]
The commit fixes it for me too, thank you.
