### ISSUE TITLE
Exception caught

### ISSUE THREAD

**Issue by naksitrallid** [Icinga/icingaweb2-module-graphite#88]
> Warning: Exception caught by form: Plugin by name 'Date' was not found in the registry; used paths: Icinga\Web\Form\Element\: /usr/share/php/Icinga/Web/Form/Element/ Zend_Form_Element_: Zend/Form/Element/ Stack Trace: #0 /usr/share/icingaweb2/library/vendor/Zend/Form.php(1122): Zend_Loader_PluginLoader->load('Date') #1 /usr/share/php/Icinga/Web/Form.php(932): Zend_Form->createElement('date', 'start_date', Array) #2 /usr/share/icingaweb2/library/vendor/Zend/Form.php(1035): Icinga\Web\Form->createElement('date', 'start_date', Array) #3 /usr/share/icingaweb2/library/vendor/Zend/Form.php(1176): Zend_Form->addElement('date', 'start_date', Array) #4 /usr/share/icingaweb2/modules/graphite/application/forms/TimeRangePicker/CustomForm.php(82): Zend_Form->addElements(Array) #5 /usr/share/php/Icinga/Web/Form.php(772): Icinga\Module\Graphite\Forms\TimeRangePicker\CustomForm->createElements(Array) #6 /usr/share/php/Icinga/Web/Form.php(1541): Icinga\Web\Form->create() #7 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2990): Ici in /usr/share/icingaweb2/library/vendor/Zend/Form.php on line 2995

## Steps to Reproduce (for bugs)

1. navigate Graphite
2. chose Hosts or Services (doesn't matter)
3. scroll down to bottom
4. read the messages i quoted in summary of an issue

## Your Environment

* Module version (System - About): 0.0.0 (b224e6f7094b53fcdad3ecdb3bc9df81e0630b0f)
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`):  r2.8.0-1
* Operating System and version: Debian 9.2 (Stretch)
* Webserver, PHP versions: Apache 2.4.25, PHP 7.0.19-1

**Comment by R00T88** [comment]
i got this message on host and service view under graphite menu

Warning: Exception caught by form: Plugin by name 'Date' was not found in the registry; used paths: Icinga\Web\Form\Element\: /usr/share/php/Icinga/Web/Form/Element/ Zend_Form_Element_: Zend/Form/Element/ Stack Trace: #0 /usr/share/icingaweb2/library/vendor/Zend/Form.php(1122): Zend_Loader_PluginLoader->load('Date') #1 /usr/share/php/Icinga/Web/Form.php(932): Zend_Form->createElement('date', 'start_date', Array) #2 /usr/share/icingaweb2/library/vendor/Zend/Form.php(1035): Icinga\Web\Form->createElement('date', 'start_date', Array) #3 /usr/share/icingaweb2/library/vendor/Zend/Form.php(1176): Zend_Form->addElement('date', 'start_date', Array) #4 /usr/share/icingaweb2/modules/graphite/application/forms/TimeRangePicker/CustomForm.php(82): Zend_Form->addElements(Array) #5 /usr/share/php/Icinga/Web/Form.php(772): Icinga\Module\Graphite\Forms\TimeRangePicker\CustomForm->createElements(Array) #6 /usr/share/php/Icinga/Web/Form.php(1541): Icinga\Web\Form->create() #7 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2990): Ici in /usr/share/icingaweb2/library/vendor/Zend/Form.php on line 2995

**Comment by naksitrallid** [comment]
this problem was solved for me by performing an Icingaweb2 upgrade (2.4.2-1 -> 2.5.0-1) - i use Icinga2 and Icingaweb2 packages from [their official repository](http://packages.icinga.com/debian/). @R00T88 i hope this will help you too

**Comment by R00T88** [comment]
thank @naksitrallid that fixed the error but still no graph present in detailed view of host/service

![image](https://user-images.githubusercontent.com/9050487/33446631-f394d1e0-d600-11e7-86e9-6526e0b510f4.png)

**Comment by lazyfrosch** [comment]
The module explicitly requires Icinga Web >= 2.5.0, which is documented now:

https://github.com/Icinga/icingaweb2-module-graphite/blob/master/doc/02-Installation.md#requirements
