### ISSUE TITLE
no charts in host/service detail view - only from Graphite main menu

### ISSUE THREAD

**Issue by naksitrallid** [Icinga/icingaweb2-module-graphite#89]
i can see no charts (nothing! no trace or error!) in Host/Service tabs, yet i know for sure charts are working because i can see them utilizing Hosts/Services elements from Graphite main menu element

## Current Behavior

i can see no errors in Apache error.log

## Possible Solution

i would like to hear it from you

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Module version (System - About): 0.0.0 (b224e6f7094b53fcdad3ecdb3bc9df81e0630b0f)
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): r2.8.0-1
* Operating System and version: Debian 9.2 (Stretch)
* Webserver, PHP versions: Apache 2.4.25, PHP 7.0.19-1

**Comment by R00T88** [comment]
i have the same problem.
No charts display in detailed view host/service

**Comment by naksitrallid** [comment]
this problem was solved for me by performing an Icingaweb2 upgrade (2.4.2-1 -> 2.5.0-1) - i use Icinga2 and Icingaweb2 packages from their official repository. @R00T88 i hope this will help you too

**Comment by dnsmichi** [comment]
@naksitrallid thanks for the heads up. The installation documentation highlights the required versions, and as such you need to use `Icinga Web 2 (>= 2.5.0)`.
