### ISSUE TITLE
[dev.icinga.com #12323] Show action link only when there is performance data available

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-graphite#9]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12323

**Created by p0nts on 2016-08-06 17:02:30 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-06 17:02:30 +00:00 (in Redmine)_

---

It seems that the Action link towards the graphite graph is always shown, even if there is no graph available for that specific service.

Nice feature request to only show the action link when there actualy is performance data connected to the service

**Comment by Al2Klimov** [comment]
This has already been fixed another way.
