### ISSUE TITLE
Saving config.ini

### ISSUE THREAD

**Issue by R00T88** [Icinga/icingaweb2-module-graphite#90]
I'm not able to save config.ini file in path  /etc/icingaweb2/modules/graphite/ when try to config grapite module on icinga 2.8.0
i got permission error but i was able to config other icinga2 module

![image](https://user-images.githubusercontent.com/9050487/33446116-4eeccfae-d5ff-11e7-93f5-01e349306360.png)

**Comment by dnsmichi** [comment]
Please fill in the issue template and provide addition information about your system. 

- Icinga Web 2 version
- Webserver, PHP version
- For that specific problem: As the GUI states, permissions from `ls -lahR /etc/icingaweb2/modules`, anything logged to the application log? SELinux, Operating system?

**Comment by R00T88** [comment]
- Icinga2 version r2.8.0-1
- Icingaweb2 version 2.5.0
- OS: Ubuntu 16.04.3 LTS

i post the permission on modules folder

![image](https://user-images.githubusercontent.com/9050487/33472189-66b338ae-d671-11e7-8b53-52d5b6083dc5.png)

**Comment by lippserd** [comment]
Look at the permissions and the owner of `modules/graphite/config.ini`. It seems that you've created the file beforehand as user root. Just remove the file and save it again via the UI.
