### ISSUE TITLE
Plugin does not parse https graphite URLs properly

### ISSUE THREAD

**Issue by smelchior** [Icinga/icingaweb2-module-graphite#91]
## Expected Behavior

Our Icinga installation is configured at:
https://icinga.example.com
Graphite is at:
https://icinga.example.com/graphite-web/

The plugin should use the configured url to fetch the graphs.

## Current Behaviour

The host part of the URL is missing when the plugin tries to request data from graphite. We get the message:
```
Could not resolve host: graphite-web
```
when looking at a service detail page.

Currently library/Graphite/Graphing/GraphingTrait.php uses `Url::fromPath($graphite->url)` to parse the url from the configuration. The function seems to remove the host attribute if the hostname is the same as the one from icinga. The object looks like this:
```
object(Icinga\Web\Url)#677 (10) { ["external":protected]=> NULL ["params":protected]=> object(Icinga\Web\UrlParams)#691 (3) { ["separator":protected]=> string(1) "&" ["params":protected]=> array(0) { } ["index":protected]=> array(0) { } } ["anchor":protected]=> string(0) "" ["path":protected]=> string(14) "/graphite-web/" ["basePath":protected]=> NULL ["host":protected]=> NULL ["port":protected]=> NULL ["scheme":protected]=> NULL ["username":protected]=> NULL ["password":protected]=> NULL }
```

## Possible Solution
Url::fromPath is probably not the correct function to use in this case? Maybe it should be checked if ->host is empty and the icinga2 hostname should be added?

## Steps to Reproduce (for bugs)
see expected behaviour

## Your Environment
* Module version (System - About): 0.0.0 (current git master
* Icinga Web 2 version and modules (System - About): 2.5.0
* Icinga 2 version (`icinga2 --version`): 2.5.0
* Operating System and version: Debian Stretch
* Webserver, PHP versions: Apache 2.4 + PHP 7.0.

**Comment by Al2Klimov** [comment]
Hello @smelchior and thank you for your report!

Please could you try the latest Git master and – in case of failure – tell your exact URL as configured in Modules > graphite > Backend.

Best,
AK

**Comment by smelchior** [comment]
Hi @Al2Klimov,
thanks for looking into this.
I switched to the latest git master and the issue still persists as described. The graphite url configured is:
https://mymonitoring-domain.com/graphite-web/

The icingaweb installation resides in:
https://mymonitoring-domain.com/
Regards,
Seb

**Comment by Al2Klimov** [comment]
Hello @smelchior,

Please could you test the above pull request's changes?

Best,
AK

**Comment by smelchior** [comment]
I tried the branch and everything works as expected 👍

**Comment by smelchior** [comment]
thanks again for your work on this 👍
