### ISSUE TITLE
custom default pre-selection range

### ISSUE THREAD

**Issue by teclogi** [Icinga/icingaweb2-module-graphite#93]
## Expected Behavior

There should be a way to set a custom default  pre-selection range for the graphs.
config.ini file?

## Your Environment

* Module version (System - About): 0.9.0
* Icinga Web 2 version and modules (System - About): 2.5.0
* Icinga 2 version (`icinga2 --version`): r2.8.0-1
* Operating System and version: Debian Stretch
* Webserver, PHP versions: Apache 2.4 + PHP 7.0

**Comment by BjoernRobbe** [comment]
Instead of using the config.ini file for that, I would prefer to set the default timerange in the template files.
So you can have different pre-default time ranges for different check commands.
