### ISSUE TITLE
Auto refresh graphs with "long time range" causes high cpu load on server

### ISSUE THREAD

**Issue by BjoernRobbe** [Icinga/icingaweb2-module-graphite#94]
If you choose a graph with i.e. 6 months, let the browser window opened, it seems that the
"auto refresh" of the graphs causes high cpu load on the webserver.

Maybe, an option for auto-refresh?

top:
>     2933 apache    20   0  445m  77m 7176 R 94.5  1.3   1:14.35 httpd
>     3379 apache    20   0  440m  73m 7176 R 93.5  1.2   1:24.79 httpd

## Steps to Reproduce (for bugs)

1. Open a Host/Service in browser with graphs, choose a 6 months graph, let browser window open
2. linux: top

## Your Environment

* Module version (System - About): 0.9.0
* Icinga Web 2 version and modules (System - About): 2.5.0
* Icinga 2 version (`icinga2 --version`): r2.8.0-1
* Operating System and version: CentOS 6.9
* Webserver, PHP versions: Apache 2.2.5 + PHP-FPM 7.0

**Comment by Al2Klimov** [comment]
@bobapple Any opinion on this?

**Comment by bobapple** [comment]
First of all, we should try to reproduce this. As I understand it, it's Apache that's causing the high load. I see no reason why this would happen with just a few requests. It needs further investigation

**Comment by bobapple** [comment]
@BjoernRobbe I'm not able to reproduce this behaviour. Please re-open the issue if you have more details.

**Comment by BjoernRobbe** [comment]
@bobapple Thanks for investigating. Finding out that the high cpu load is on the webserver which runs graphite. On our installation icingaweb2 and graphite running on the same server.
Setting up icingaweb2 on another server, the high cpu load is NOT on the icingaweb2 server, but on the graphite server. Maybe a graphite problem or a misconfigured setup.

**Comment by bakkerl** [comment]
The graphs from the module are refreshed every 2 seconds when displayed. This causes the load.
Is there an option to set this refresh period?

**Comment by kajla** [comment]
Same here. Please add the refresh time period option to settings.
Thanks.
