### ISSUE TITLE
Add option to disable "no graphs found"

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingaweb2-module-graphite#99]
By default, the text "no graphs found" is displayed on the Graphite Host/Service overview page if no data was found.

The user should be allowed to disable this behaviour so nothing gets displayed if no data was found.

**Comment by Al2Klimov** [comment]
Imagine you go to your graphs list and you see the pagination controls, but no content. IMO this wouldn't be very intuitive.

**Comment by bobapple** [comment]
The default should be to display "no grpahs found", like we have now. We still need an option for those who "know what they are doing".
